/* Generated by Together */

#include <iostream>
#include "GroupServerApp.h"
#include "GameCommon.h"
#include "CommFunc.h"
#include "DBConnect.h"
#include "Team.h"

// 计时退出机制宏切换
//#define CHAEXIT_ONTIME

LoginManageList::LoginManageList() {
	InitializeCriticalSection(&m_cs);
}

LoginManageList::~LoginManageList() {
	DeleteCriticalSection(&m_cs);
}

bool LoginManageList::Insert(const std::string& name) {
	bool ret = false;
	Lock();
	if (!_Query(name)) {
		m_list.push_back(name);
		ret = true;
	}
	UnLock();
	return ret;
}

bool LoginManageList::Remove(const std::string& name) {
	bool ret = false;
	Lock();

	auto it = std::find(m_list.begin(), m_list.end(), name);
	if (it != m_list.end()) {
		ret = true;
		m_list.erase(it);
	}
	UnLock();
	return ret;
}

bool LoginManageList::Query(const std::string& name) {
	bool ret = false;
	Lock();
	ret = _Query(name);
	UnLock();
	return ret;
}

bool LoginManageList::_Query(const std::string& name) {
	auto it = std::find(m_list.cbegin(), m_list.cend(), name);
	if (it != m_list.end()) {
		return true;
	}
	return false;
}

void LoginManageList::Lock() {
	EnterCriticalSection(&m_cs);
}

void LoginManageList::UnLock() {
	LeaveCriticalSection(&m_cs);
}

bool GroupServerApp::OnConnect(DataSocket* datasock) //返回值:true-允许连接,false-不允许连接
{
	datasock->SetRecvBuf(64 * 1024);
	datasock->SetSendBuf(64 * 1024);
	if (!datasock->IsServer()) {
		LogLine l_line(g_LogConnect);
		l_line << newln << "AccountServer:" << datasock->GetPeerIP() << "," << datasock->GetPeerPort() << "come ! Socket num:"
			   << GetSockTotal() + 1 << endln;
		std::cout << "AccountServer:" << datasock->GetPeerIP() << "," << datasock->GetPeerPort() << "come ! Socket num:" << GetSockTotal() + 1 << std::endl;
	} else {
		LogLine l_line(g_LogConnect);
		l_line << newln << "GateServer:" << datasock->GetPeerIP() << "," << datasock->GetPeerPort() << "come ! Socket num:"
			   << GetSockTotal() + 1 << endln;
		std::cout << "GateServer:" << datasock->GetPeerIP() << "," << datasock->GetPeerPort() << "come ! Socket num:" << GetSockTotal() + 1 << std::endl;
	}
	return true;
}

void GroupServerApp::OnDisconnect(DataSocket* datasock, int reason) {
	if (!datasock->IsServer()) {
		m_mtxlogin.lock();
		try {
			if (g_gpsvr->m_acctsock == datasock) {
				g_gpsvr->m_acctsock = nullptr;
			}
		} catch (...) {
		}
		m_mtxlogin.unlock();
		LogLine l_line(g_LogConnect);
		l_line << newln << "AccountServer:" << datasock->GetPeerIP() << "," << datasock->GetPeerPort() << "go ! Socket num:"
			   << GetSockTotal() << "reason=(" << reason << ")" << GetDisconnectErrText(reason)
			   << endln;
		std::cout << "AccountServer:" << datasock->GetPeerIP() << "," << datasock->GetPeerPort() << "go ! Socket num:" << GetSockTotal() << "reason=" << GetDisconnectErrText(reason).c_str() << std::endl;

		if (reason == DS_SHUTDOWN || reason == DS_DISCONN) {
			return;
		}

		std::cout << "after 5 seconds reconnect......" << std::endl;
		Sleep(5000);
		InitACTSvrConnect(*g_gpsvr);
	} else {
		auto l_gate = static_cast<GateServer*>(datasock->GetPointer());
		if (l_gate) {
			m_mtxlogin.lock();
			try {
				l_gate->SetDataSock(nullptr);
			} catch (...) {
			}
			m_mtxlogin.unlock();
			LogLine l_line(g_LogConnect);
			l_line << newln << "GateServer:" << datasock->GetPeerIP() << "," << datasock->GetPeerPort() << "go ! Socket num:"
				   << GetSockTotal() << "reason=(" << reason << ")" << GetDisconnectErrText(reason)
				   << endln;
			std::cout << "GateServer:" << datasock->GetPeerIP() << "," << datasock->GetPeerPort() << "go ! Socket num:" << GetSockTotal() << "reason=" << GetDisconnectErrText(reason).c_str() << std::endl;

			Player* player{nullptr};
			RunChainGetArmor<Player> l(m_plylst);
			while (player = m_plylst.GetNextItem()) {
				if (player->m_gate == l_gate) {
					RPacket l_rpk;
					TP_USER_LOGOUT(player, datasock, l_rpk);
				}
			}
			l.unlock();
		}
	}
}

WPacket GroupServerApp::OnServeCall(DataSocket* datasock, RPacket& pk) {
	const unsigned short l_cmd = pk.ReadCmd();
	switch (l_cmd) {
	case CMD_TP_LOGIN:
		return TP_LOGIN(datasock, pk);
	case CMD_TP_USER_LOGIN:
		return TP_USER_LOGIN(datasock, pk);
	case CMD_TP_REQPLYLST:
		return TP_REQPLYLST(datasock, pk);
	case CMD_TP_SYNC_PLYLST:
		return TP_SYNC_PLYLST(datasock, pk);
	case CMD_OS_LOGIN:
		return OS_LOGIN(datasock, pk);
	}

	auto* player = ToPointer<Player>(pk.ReverseReadAddress());
	const uintptr_t l_gtaddr = pk.ReverseReadAddress();
	uintptr_t playergt = 0;
	try {
		playergt = player->m_gtAddr;
	} catch (...) {
		player = nullptr;
	}
	if (!player || l_gtaddr != playergt) {
		WPacket l_retpk = GetWPacket();
		l_retpk.WriteShort(ERR_PT_KICKUSER);
		return l_retpk;
	}

	switch (l_cmd) {
	case CMD_TP_USER_LOGOUT:
		return TP_USER_LOGOUT(player, datasock, pk);
	case CMD_TP_BGNPLAY:
		return TP_BGNPLAY(player, datasock, pk);
	case CMD_TP_ENDPLAY:
		return TP_ENDPLAY(player, datasock, pk);
	case CMD_TP_NEWCHA:
		return TP_NEWCHA(player, datasock, pk);
	case CMD_TP_DELCHA:
		return TP_DELCHA(player, datasock, pk);
	case CMD_TP_CREATE_PASSWORD2:
		return TP_CREATE_PASSWORD2(player, datasock, pk);
	case CMD_TP_UPDATE_PASSWORD2:
		return TP_UPDATE_PASSWORD2(player, datasock, pk);
	}
	return WPacket(nullptr);
}

void GroupServerApp::OnProcessData(DataSocket* datasock, RPacket& recvbuf) {
	try {
		const unsigned short l_cmd = recvbuf.ReadCmd();
		switch (l_cmd) {
		case CMD_AP_KICKUSER: {

			recvbuf.ReadShort();
			AP_KICKUSER(datasock, recvbuf);
			return;
		}
		case CMD_AP_EXPSCALE: { //  防沉迷
			AP_EXPSCALE(datasock, recvbuf);
			return;
		}
		case CMD_TP_DISC: {
			TP_DISC(datasock, recvbuf);
			return;
		}
		case CMD_TP_ESTOPUSER_CHECK: {
			TP_ESTOPUSER_CHECK(datasock, recvbuf);
			return;
		}
		case CMD_MP_GUILD_CHALL_PRIZEMONEY: {
			MP_GUILD_CHALL_PRIZEMONEY(nullptr, datasock, recvbuf);
			return;
		}
		case CMD_OS_PING: {
			OS_PING(datasock, recvbuf);
			return;
		}
		case CMD_MP_GM1SAY1: {
			CP_GM1SAY1(nullptr, datasock, recvbuf);
			return;
		}
		case CMD_MP_GM1SAY: {
			CP_GM1SAY(nullptr, datasock, recvbuf);
			return;
		}
		}

		auto* player = ToPointer<Player>(recvbuf.ReverseReadAddress());
		uintptr_t l_gtaddr = recvbuf.ReverseReadAddress();
		try {
			if (!player || (l_cmd != CMD_MP_ENTERMAP && player->m_currcha < 0) || l_gtaddr != player->m_gtAddr) {
				//std::cout<<"l_cmd ="<<l_cmd<<"\tplayer ="<<ToAddress(player)<<"\tl_gtaddr ="<<l_gtaddr<<std::endl;
				//if(player)
				//{
				//	std::cout<<"player->m_currcha ="<<player->m_currcha<<std::endl;
				//	std::cout<<"player->m_gtAddr ="<<player->m_gtAddr<<std::endl;
				//}

				KickUser(datasock, ToAddress(player), l_gtaddr);
				return;
			}
		} catch (...) {
			//std::cout<<"exception"<<std::endl;
			KickUser(datasock, ToAddress(player), l_gtaddr);
			return;
		}
		switch (l_cmd) {
		case CMD_CP_PING: {
			CP_PING(player, datasock, recvbuf);
			return;
		}
		case CMD_CP_REPORT_WG: {
			CP_REPORT_WG(player, datasock, recvbuf);
			return;
		}
		case CMD_MP_GUILD_MOTTO: {
			MP_GUILD_MOTTO(player, datasock, recvbuf);
			return;
		}
		case CMD_MP_GUILD_CHALLMONEY: {
			MP_GUILD_CHALLMONEY(player, datasock, recvbuf);
			return;
		}
		case CMD_MP_GUILD_DISBAND: {
			MP_GUILD_DISBAND(player, datasock, recvbuf);
			return;
		}
		case CMD_MP_GUILD_LEAVE: {
			MP_GUILD_LEAVE(player, datasock, recvbuf);
			return;
		}
		case CMD_MP_GUILD_KICK: {
			MP_GUILD_KICK(player, datasock, recvbuf);
			return;
		}
		case CMD_MP_GUILD_CREATE: {
			MP_GUILD_CREATE(player, datasock, recvbuf);
			return;
		}
		case CMD_MP_GUILD_APPROVE: {
			MP_GUILD_APPROVE(player, datasock, recvbuf);
			return;
		}
		case CMD_CP_GUILD_INVITE: {
			CP_GUILD_INVITE(player, datasock, recvbuf);
			return;
		}
		case CMD_CP_GUILD_ACCEPT: {
			CP_GUILD_ACCEPT(player, datasock, recvbuf);
			return;
		}
		case CMD_CP_GUILD_REFUSE: {
			CP_GUILD_REFUSE(player, datasock, recvbuf);
			return;
		}
		case CMD_MP_SAY2ALL: {
			MP_SAY2ALL(player, datasock, recvbuf);
			return;
		}
		case CMD_MP_SAY2TRADE: {
			MP_SAY2TRADE(player, datasock, recvbuf);
			return;
		}
		case CMD_CP_REFUSETOME: {
			CP_REFUSETOME(player, datasock, recvbuf);
			return;
		}
		case CMD_CP_GM1SAY: {
			CP_GM1SAY(player, datasock, recvbuf);
			return;
		}
#ifdef MANAGE_VER
		case CMD_CP_GMSAY: {
			CP_GMSAY(player, datasock, recvbuf);
			return;
		}
#endif
		case CMD_CP_GM1SAY1: {
			CP_GM1SAY1(player, datasock, recvbuf);
			return;
		}
		case CMD_CP_SAY2TRADE: {
			CP_SAY2TRADE(player, datasock, recvbuf);
			return;
		}
		case CMD_CP_SAY2ALL: {
			CP_SAY2ALL(player, datasock, recvbuf);
			return;
		}
		case CMD_CP_SAY2YOU: {
			CP_SAY2YOU(player, datasock, recvbuf);
			return;
		}
		case CMD_CP_SAY2TEM: {
			CP_SAY2TEM(player, datasock, recvbuf);
			return;
		}
		case CMD_CP_SAY2GUD: {
			CP_SAY2GUD(player, datasock, recvbuf);
			return;
		}
		case CMD_CP_TEAM_INVITE: {
			CP_TEAM_INVITE(player, datasock, recvbuf);
			return;
		}
		case CMD_CP_TEAM_ACCEPT: {
			CP_TEAM_ACCEPT(player, datasock, recvbuf);
			return;
		}
		case CMD_CP_TEAM_REFUSE: {
			CP_TEAM_REFUSE(player, datasock, recvbuf);
			return;
		}
		case CMD_CP_TEAM_LEAVE: {
			CP_TEAM_LEAVE(player, datasock, recvbuf);
			return;
		}
		case CMD_CP_TEAM_KICK: {
			CP_TEAM_KICK(player, datasock, recvbuf);
			return;
		}
		case CMD_MP_TEAM_CREATE: {
			MP_TEAM_CREATE(player, datasock, recvbuf);
			return;
		}
		case CMD_MP_ENTERMAP: {
			MP_ENTERMAP(player, datasock, recvbuf);
			return;
		}
		case CMD_MP_MASTER_CREATE: {
			MP_MASTER_CREATE(player, datasock, recvbuf);
			return;
		}
		case CMD_MP_MASTER_DEL: {
			MP_MASTER_DEL(player, datasock, recvbuf);
			return;
		}
		case CMD_MP_MASTER_FINISH: {
			MP_MASTER_FINISH(player, datasock, recvbuf);
			return;
		}
		case CMD_CP_MASTER_REFRESH_INFO: {
			CP_MASTER_REFRESH_INFO(player, datasock, recvbuf);
			return;
		}
		case CMD_CP_PRENTICE_REFRESH_INFO: {
			CP_PRENTICE_REFRESH_INFO(player, datasock, recvbuf);
			return;
		}
		case CMD_CP_FRND_INVITE: {
			CP_FRND_INVITE(player, datasock, recvbuf);
			return;
		}
		case CMD_CP_FRND_ACCEPT: {
			CP_FRND_ACCEPT(player, datasock, recvbuf);
			return;
		}
		case CMD_CP_FRND_REFUSE: {
			CP_FRND_REFUSE(player, datasock, recvbuf);
			return;
		}
		case CMD_CP_FRND_DELETE: {
			CP_FRND_DELETE(player, datasock, recvbuf);
			return;
		}
		case CMD_CP_FRND_DEL_GROUP: {
			CP_FRND_DEL_GROUP(player, datasock, recvbuf);
			return;
		}
		case CMD_CP_FRND_ADD_GROUP: {
			CP_FRND_ADD_GROUP(player, datasock, recvbuf);
			return;
		}
		case CMD_CP_FRND_MOVE_GROUP: {
			CP_FRND_MOVE_GROUP(player, datasock, recvbuf);
			return;
		}
		case CMD_CP_FRND_CHANGE_GROUP: {
			CP_FRND_CHANGE_GROUP(player, datasock, recvbuf);
			return;
		}
		case CMD_CP_FRND_REFRESH_INFO: {
			CP_FRND_REFRESH_INFO(player, datasock, recvbuf);
			return;
		}
		case CMD_CP_CHANGE_PERSONINFO: {
			CP_CHANGE_PERSONINFO(player, datasock, recvbuf);
			return;
		}
		case CMD_CP_QUERY_PERSONINFO: {
			CP_QUERY_PERSONINFO(player, datasock, recvbuf);
			return;
		}
		case CMD_CP_SESS_CREATE: {
			CP_SESS_CREATE(player, datasock, recvbuf);
			return;
		}
		case CMD_CP_SESS_SAY: {
			CP_SESS_SAY(player, datasock, recvbuf);
			return;
		}
		case CMD_CP_SESS_ADD: {
			CP_SESS_ADD(player, datasock, recvbuf);
			return;
		}
		case CMD_CP_SESS_LEAVE: {
			CP_SESS_LEAVE(player, datasock, recvbuf);
			return;
		}
		case CMD_MP_GARNER2_CGETORDER: {
			CP_GARNER2_GETORDER(player, datasock, recvbuf);
			return;
		}
		case CMD_MP_GARNER2_UPDATE: { //反斗白银，更新最新的排名
			MP_GARNER2_UPDATE(player, datasock, recvbuf);
			return;
		}
		case CMD_MP_GMBANACCOUNT: {
			MP_GM_BANACCOUNT(player, datasock, recvbuf);
			return;
		}
		}
	} catch (...) {
		return;
	}
}

WPacket GroupServerApp::TP_SYNC_PLYLST(DataSocket* datasock, RPacket& pk) {
	WPacket l_retpk = GetWPacket();

	m_mtxSyn.lock();

	try {
		const unsigned long num = pk.ReadLong();
		const char* l_gatename = pk.ReadString();
		GateServer* pServer = this->FindGateSByName(l_gatename);

		if (pServer) {
			l_retpk.WriteShort(ERR_SUCCESS);

			l_retpk.WriteShort((unsigned short)num);
			for (int i = 0; i < (int)num; i++) {
				Player* player = g_gpsvr->m_plyheap.Get();
				if (player) {
					l_retpk.WriteShort(1);
					l_retpk.WriteAddress(ToAddress(player));

					player->m_gate = pServer;
					player->m_gtAddr = pk.ReadAddress();
					player->m_acctLoginID = pk.ReadLong();
					player->m_acctid = pk.ReadLong();

					player->BeginRun();
				} else {
					l_retpk.WriteShort(0);
				}
			}
		} else
			l_retpk.WriteShort(ERR_PT_LOGFAIL);
	} catch (...) {
		l_retpk.WriteShort(ERR_PT_LOGFAIL);
	}
	m_mtxSyn.unlock();

	return l_retpk;
}

WPacket GroupServerApp::OS_LOGIN(DataSocket* datasock, RPacket& pk) {
	WPacket l_retpk = GetWPacket();
	if (pk.ReadShort() != atoi(m_cfg["Main"]["Version"])) {
		l_retpk.WriteShort(ERR_OS_NOTMATCH_VERSION);
		Disconnect(datasock, 100, -15);
		return l_retpk;
	}
	const char* agentName = pk.ReadString();

	LogLine l_line(g_LogConnect);
	l_line << newln << "AgentServer:" << datasock->GetPeerIP() << "," << datasock->GetPeerPort() << "OS_LOGIN1" << endln;

	m_mtxAgent.lock();

	l_line << newln << "AgentServer:" << datasock->GetPeerIP() << "," << datasock->GetPeerPort() << "OS_LOGIN2" << endln;
	try {
		if (m_groupServerAgent.SetDataSock(datasock)) {
			l_retpk.WriteShort(ERR_SUCCESS);
			std::cout << "AgentServer:" << datasock->GetPeerIP() << "," << datasock->GetPeerPort() << "Re-log successful!" << std::endl;
		} else {
			l_retpk.WriteShort(ERR_PT_SAMEGATENAME);
			std::cout << "AgentServer:" << datasock->GetPeerIP() << "," << datasock->GetPeerPort() << "Login failed: A same name is already logged on in AgentServer" << std::endl;
			Disconnect(datasock);
		}
	} catch (...) {
	}
	m_mtxAgent.unlock();
	l_line << newln << "AgentServer:" << datasock->GetPeerIP() << "," << datasock->GetPeerPort() << "OS_LOGIN3" << endln;

	return l_retpk;
}

void GroupServerApp::OS_PING(DataSocket* datasock, RPacket& pk) {
	WPacket wpk = GetWPacket();
	wpk.WriteCmd(CMD_SO_PING);
	wpk.WriteLong(m_plyheap.GetUsedNum());

	SendData(datasock, wpk);
}
// End

void GroupServerApp::CP_PING(Player* ply, DataSocket* datasock, RPacket& pk) {
	Player* player = ply->m_pingply;
	if (!player)
		return;
	ply->m_pingply = nullptr;
	char l_buf[256];
	_snprintf_s(l_buf, sizeof(l_buf), _TRUNCATE, RES_STRING(GP_GROUPSERVERAPPMASTER_CPP_00001), ply->m_chaname[ply->m_currcha].c_str(), pk.ReadLong());
	player->SendSysInfo(l_buf);
}

void GroupServerApp::CP_REPORT_WG(Player* ply, DataSocket* datasock, RPacket& pk) {
	// 统计玩家使用外挂数量
	if (!ply->m_bWG) {
		ply->m_bWG = true;
		m_curWGChaNum++;
	}
	//ply->SendSysInfo( "报告了角色使用外挂！" );
}

void GroupServerApp::KickUser(DataSocket* datasock, uintptr_t gpaddr, uintptr_t gtaddr) {
	WPacket wpk = GetWPacket();
	wpk.WriteCmd(CMD_PT_KICKUSER);
	wpk.WriteAddress(gpaddr);
	wpk.WriteAddress(gtaddr);
	wpk.WriteShort(1);
	SendData(datasock, wpk);
}

WPacket GroupServerApp::TP_LOGIN(DataSocket* datasock, RPacket& pk) {
	WPacket l_retpk = GetWPacket();
	if (pk.ReadShort() != atoi(m_cfg["Main"]["Version"])) {
		l_retpk.WriteShort(ERR_PT_LOGFAIL);
		Disconnect(datasock, 100, -15);
		return l_retpk;
	}
	cChar* l_gatename = pk.ReadString();
	LogLine l_line(g_LogConnect);
	l_line << newln << "GateServer:" << datasock->GetPeerIP() << "," << datasock->GetPeerPort() << "TP_LOGIN1" << endln;

	m_mtxlogin.lock();
	l_line << newln << "GateServer:" << datasock->GetPeerIP() << "," << datasock->GetPeerPort() << "TP_LOGIN2" << endln;

	try {
		GateServer* l_gate = FindGateSByName(l_gatename);
		if (l_gate) {
			if (l_gate->SetDataSock(datasock)) {
				l_gate->SetSync();

				l_retpk.WriteShort(ERR_SUCCESS);
				std::cout << "GateServer:" << datasock->GetPeerIP() << "," << datasock->GetPeerPort() << "re login success!" << std::endl;
			} else {
				l_retpk.WriteShort(ERR_PT_SAMEGATENAME);
				std::cout << "GateServer:" << datasock->GetPeerIP() << "," << datasock->GetPeerPort() << "login failed: exsit the same name's GateServer " << std::endl;
				Disconnect(datasock);
			}
		} else if (m_gatenum < GATE_MAX) {
			m_gate[m_gatenum].SetSync();

			l_retpk.WriteShort(ERR_SUCCESS);
			m_gate[m_gatenum].m_name = l_gatename;
			m_gate[m_gatenum].SetDataSock(datasock);
			m_gatenum++;
			std::cout << "GateServer:" << datasock->GetPeerIP() << "," << datasock->GetPeerPort() << "login success" << std::endl;
		} else {
			l_retpk.WriteShort(ERR_PT_LOGFAIL);
			std::cout << "GateServer:" << datasock->GetPeerIP() << "," << datasock->GetPeerPort() << "login failed!" << std::endl;
			Disconnect(datasock);
		}
	} catch (...) {
	}
	m_mtxlogin.unlock();
	l_line << newln << "GateServer:" << datasock->GetPeerIP() << "," << datasock->GetPeerPort() << "TP_LOGIN3" << endln;

	return l_retpk;
}

WPacket GroupServerApp::TP_REQPLYLST(DataSocket* datasock, RPacket& pk) {
	auto* l_gate = static_cast<GateServer*>(datasock->GetPointer());
	if (!l_gate) {
		return nullptr;
	}
	WPacket l_retpk = GetWPacket();
	Player* player{nullptr};
	unsigned short playernum = 0;
	RunChainGetArmor<Player> l(m_plylst);
	for (player = m_plylst.GetNextItem(); player; player = m_plylst.GetNextItem()) {
		if (player->m_gate != l_gate || player->m_currcha < 0)
			continue;
		l_retpk.WriteAddress(player->m_gtAddr);
		l_retpk.WriteLong(player->m_chaid[player->m_currcha]);
		playernum++;
	}
	l.unlock();
	l_retpk.WriteShort(playernum);
	return l_retpk;
}

bool GroupServerApp::GetCHAsFromDBByPlayer(Player* player, WPacket& wpk) {
	MutexArmor l_lockDB(m_mtxDB);

	const int affected_row_count = m_tblaccounts->FetchRowByActName(player->m_acctname.c_str());
	switch (affected_row_count) {
	case 0: { // New account, does not yet exist in GameDB.account table
		player->m_bNew = true;
		player->m_password.clear();
		//if( !m_tblaccounts->InsertRow(player->m_acctLoginID,player->m_acctname.c_str(),"0") )
		if (!m_tblaccounts->InsertRow(player->m_acctLoginID, player->m_acctname.c_str(), "0", atoi(m_cfg["account"]["equal"]) == 1 ? true : false)) {
			return false;
		}
		if (!m_tblaccounts->FetchRowByActName(player->m_acctname.c_str())) {
			return false;
		}
		player->m_acctid = m_tblaccounts->GetActID();
		wpk.WriteChar(0); //角色个数
	} break;
	case 1: { // Found unique account, read character data
		player->m_bNew = false;
		player->m_acctid = m_tblaccounts->GetActID();
		player->m_password = m_tblaccounts->GetPassword();
		player->m_gm = m_tblaccounts->GetGM();
		std::string cha_id_strings[Player::emMaxCharacters];
		player->m_chanum = static_cast<char>(Util_ResolveTextLine(m_tblaccounts->GetChaIDs(), cha_id_strings, Player::emMaxCharacters, ';'));
		wpk.WriteChar(player->m_chanum); //角色个数

		char player_cha_index{0};
		for (char i = 0; i < player->m_chanum; ++i) {
			const auto cha_id = std::stoi(cha_id_strings[i]);
			if (cha_id == 0) {
				wpk.WriteChar(0);
				continue;
			}
			const int affected_row_count = m_tblcharaters->FetchRowByChaID(cha_id);
			if (affected_row_count == 1) {
				std::string l_look = m_tblcharaters->GetLook(); //获取外观数据
				LOOK look;
				std::memset(&look, 0, sizeof(LOOK));
				try {
					Strin2LookData(&look, l_look);
				} catch (...) {
					LogLine l_line(g_LogGrpServer);
					l_line << newln << "enum account [" << player->m_acctname << "]'s char[ID:" << cha_id << "] find appearance data exception." << endln;
					wpk.WriteChar(0);
					continue;
				}
				wpk.WriteChar(1); //标志这个角色数据是有效的
				player->m_chaid[player_cha_index] = cha_id;
				player->m_chaname[player_cha_index] = m_tblcharaters->GetChaName();
				player->m_motto[player_cha_index] = m_tblcharaters->GetMotto();
				player->m_icon[player_cha_index] = m_tblcharaters->GetIcon();
				player->m_guild[player_cha_index] = m_tblcharaters->GetGuildID();
				wpk.WriteString(m_tblcharaters->GetChaName());				   //角色名
				wpk.WriteString(g_GetJobName(atoi(m_tblcharaters->GetJob()))); //职业名称 Modify by sunny.sun 20090212
				wpk.WriteShort(m_tblcharaters->GetDegree());				   //等级
				wpk.WriteSequence(reinterpret_cast<const char*>(&look), sizeof(LOOK));
				++player_cha_index;
			} else {
				wpk.WriteChar(0);
				LogLine l_line(g_LogGrpServer);
				if (affected_row_count == 0) {
					l_line << newln << "enum account[" << player->m_acctname << "]'s char[ID:" << cha_id << "] can't find data in table character.";
				} else {
					l_line << newln << "enum account[" << player->m_acctname << "]'s char[ID:" << cha_id << "] database exception.";
				}
			}
		}
		player->m_chanum = player_cha_index;
	} break;
	default: {
		LogLine l_line(g_LogGrpServer);
		l_line << newln << "enum account[" << player->m_acctname << "] operate table account failed";
	} break;
	}
	return true;
}

WPacket GroupServerApp::TP_USER_LOGIN(DataSocket* datasock, RPacket& pk) {
	unsigned long l_ulMilliseconds = 25 * 1000;
	const unsigned long l_tick = GetTickCount() - pk.GetTickCount();

	if (l_ulMilliseconds > l_tick) {
		l_ulMilliseconds = l_ulMilliseconds - l_tick;

		if (m_plylst.GetTotal() >= const_cha.MaxLoginUsr) {
			auto retpk = GetWPacket();
			retpk.WriteShort(ERR_MC_TOOMANYPLY);
			return retpk;
		}

		Player* player = g_gpsvr->m_plyheap.Get();

		player->m_gate = static_cast<GateServer*>(datasock->GetPointer());
		player->m_gtAddr = pk.ReverseReadAddress();
		in_addr l_ina;
		l_ina.S_un.S_addr = pk.ReverseReadLong();
		strncpy_s(player->m_clientip, sizeof(player->m_clientip), inet_ntoa(l_ina), _TRUNCATE);

		pk.DiscardLast(static_cast<uLong>(sizeof(uShort)));
		pk.DiscardLast(sizeof(uintptr_t));

		std::string szLocale = pk.ReadString();

		uShort l_len;
		const char* l_passport = pk.ReadString(&l_len); //NOTE: e.g "nobill", not password
		if (!l_passport || strlen(l_passport) >= 64) {
			player->Free();
			auto retpk = GetWPacket();
			retpk.WriteCmd(ERR_PT_INERR);
			return retpk;
		}
		player->m_passport = l_passport;

		const char* l_acctname = pk.ReadString(&l_len); //AcctName
		if (!l_acctname || !CommConstants::Login::UsernameLengthOK(strlen(l_acctname))) {
			player->Free();
			auto retpk = GetWPacket();
			retpk.WriteShort(ERR_PT_INERR);
			return retpk;
		}
		//if(strchr(l_acctname,'\'') || !IsValidName(l_acctname,l_len))
		//{
		//	LogLine l_line(g_LogGrpServer);
		//	l_line<<newln<<"("<<player->m_clientip<<"):["<<player->m_acctname<<"]的名字中因包括非法的单引号'字符而被拒绝登录";
		//	l_line<<endln;
		//	player->Free();
		//	l_retpk =GetWPacket();
		//	l_retpk.WriteShort(ERR_PT_INVALIDDAT);
		//	return l_retpk;
		//}

		player->m_acctname = l_acctname;

		// 这里代码会导致即使密码不正确也会踢掉玩家
		// 进行帐号验证，没有存在时才能登陆
		//if(m_LoginList.Query(l_acctname))
		//{
		//          LG("AuthExcp", "Account %s multilogin at same times.1\n", l_acctname);
		//
		//	KillUserByName(l_acctname);

		//	WPacket	l_retpk	=GetWPacket();
		//	l_retpk.WriteShort(ERR_AP_LOGGED);					//错误码

		//	return l_retpk;
		//}

		WPacket wpk = pk;
		wpk.WriteCmd(CMD_PA_USER_LOGIN);
		RPacket rpkFromAccountServer = SyncCall(m_acctsock, wpk, l_ulMilliseconds); //到AccountServer认证
		if (!rpkFromAccountServer.HasData()) {
			auto retpk = GetWPacket();
			retpk.WriteShort(ERR_PT_NETEXCP); //错误码
			LogLine l_line(g_LogGrpServer);
			l_line << newln << "(" << player->m_clientip << "):[" << player->m_acctname << "] login net failed" << endln;
			player->Free();
			return retpk;
		}

		const auto l_errno = rpkFromAccountServer.ReadShort();
		if (l_errno && (rpkFromAccountServer.ReadCmd() == CMD_AP_KICKUSER)) {
			RPacket newrpk = RPacket(rpkFromAccountServer);
			AP_KICKUSER(datasock, newrpk);
			rpkFromAccountServer.DiscardLast(sizeof(uLong));
			auto retpk = static_cast<WPacket>(rpkFromAccountServer);
			return retpk;
		} else if (l_errno) {
			auto retpk = GetWPacket();
			retpk.WriteShort(l_errno); //错误码
			retpk = rpkFromAccountServer;

			LogLine l_line(g_LogGrpServer);
			l_line << newln << "(" << player->m_clientip << "):[" << player->m_acctname << "]login failed, error:" << l_errno << endln;
			player->Free();
			return retpk;
		}

		player->m_acctLoginID = rpkFromAccountServer.ReadLong();
		unsigned short l_keylen, l_textlen;
		const char* l_key = rpkFromAccountServer.ReadSequence(l_keylen);
		const char* l_text = rpkFromAccountServer.ReadSequence(l_textlen);
		player->m_sessid = rpkFromAccountServer.ReadLong();
		const std::string sessionKey = rpkFromAccountServer.ReadString();

		auto retpk = GetWPacket();
		retpk.WriteShort(ERR_SUCCESS); //成功返回值
		retpk.WriteString(sessionKey.c_str());
		retpk.WriteSequence(l_key, l_keylen); //返回加密key
		GetCHAsFromDBByPlayer(player, retpk); //进入数据库取角色列表

		constexpr auto MD5HashLength = 32;
		if (player->m_password.length() < MD5HashLength) {
			LogLine l_line(g_LogErrServer);
			l_line << newln << "account:" << player->m_acctname << "ID:" << player->m_acctid << "Key:(" << l_key << ")"
				   << "len" << l_keylen << "PW2:" << player->m_password << endln;
		}

		retpk.WriteSequence(l_text, l_textlen); //返回明文key
		retpk.WriteShort(l_textlen);

		(!player->m_password.empty() && !player->m_bNew) ? retpk.WriteChar(1)
														 : retpk.WriteChar(0);

		retpk.WriteLong(player->m_acctid);
		retpk.WriteLong(player->m_acctLoginID);
		retpk.WriteAddress(ToAddress(player)); //附带上自己的地址

		if (!m_LoginList.Insert(l_acctname)) {
			LG("AuthExcp", "Account %s multilogin at same times.2\n", l_acctname);

			KillUserByName(l_acctname);

			auto retpk = GetWPacket();
			retpk.WriteShort(ERR_AP_LOGGED); //错误码

			player->Free();
			return retpk;
		}

		player->BeginRun();

		//AddPlayerToList(player->m_chaid[player->m_currcha], player);
		LogLine l_line(g_LogGrpServer);
		l_line << newln << "(" << player->m_clientip << "):[" << player->m_acctname << "]login success, \t nline/total:" << m_plylst.GetTotal() << "/" << long(m_curChaNum) << endln;
		return retpk;
	} else {
		auto retpk = GetWPacket();
		retpk.WriteShort(ERR_PT_NETEXCP); //错误码
		LogLine l_line(g_LogGrpServer);
		l_line << newln << "authentication packet time out." << endln;
		return retpk;
	}
}

void GroupServerApp::AP_KICKUSER2(DataSocket* datasock, uLong acctid) {
	Player* player{nullptr};
	uLong l_acctid = acctid;
	RunChainGetArmor<Player> l(m_plylst);
	for (player = m_plylst.GetNextItem(); player; player = m_plylst.GetNextItem()) {
		if (player->m_acctid == l_acctid) {
			break;
		}
	}
	if (player) {
		player->EndPlay(datasock);
		if (player->EndRun()) {
			if (player->m_currcha != -1) {
				//向AccountServer发送结束计费命令
				WPacket wpk = GetWPacket();
				wpk.WriteCmd(CMD_PA_USER_BILLEND);
				wpk.WriteString(player->m_acctname.c_str());
				SendData(m_acctsock, wpk);
			}
			////向AccountServer发送LogOut命令
			WPacket wpk = GetWPacket();
			//wpk.WriteCmd(CMD_PA_USER_LOGOUT);
			//wpk.WriteLong(player->m_acctid);
			//wpk.WriteLong(player->m_sessid);
			//SendData(m_acctsock,wpk);
			//向GateServer发送踢人命令
			//wpk	=GetWPacket();
			wpk.WriteCmd(CMD_AP_KICKUSER);
			SendToClient(player, wpk);

			//踢人成功
			LogLine l_line(g_LogGrpServer);
			l_line << newln << "recieved killed acctid/acctname:[" << l_acctid << "]/[" << player->m_acctname << "] command!" << endln;
		}

		// 删除列表
		m_LoginList.Remove(player->m_acctname);
		player->Free();
	} else {
		l.unlock();
		LogLine l_line(g_LogGrpServer);
		l_line << newln << "recieved kill acctid:[" << l_acctid << "] command(not in play list)!";
	}
}

void GroupServerApp::KillUserByName(const char* accoutName) {
	Player* player{nullptr};
	RunChainGetArmor<Player> l(m_plylst);
	for (player = m_plylst.GetNextItem(); player; player = m_plylst.GetNextItem()) {
		if (strcmp(player->m_acctname.c_str(), accoutName) == 0) {
			break;
		}
	}
	if (player) {
		player->EndPlay(nullptr);
		{
			if (player->m_currcha != -1) {
				//向AccountServer发送结束计费命令
				WPacket wpk = GetWPacket();
				wpk.WriteCmd(CMD_PA_USER_BILLEND);
				wpk.WriteString(player->m_acctname.c_str());
				SendData(m_acctsock, wpk);
			}
			//向AccountServer发送LogOut命令
			WPacket wpk = GetWPacket();
			wpk.WriteCmd(CMD_PA_USER_LOGOUT);
			wpk.WriteLong(player->m_acctid);
			wpk.WriteLong(player->m_sessid);
			SendData(m_acctsock, wpk);
			//向GateServer发送踢人命令
			/*WPacket*/ wpk = GetWPacket();
			wpk.WriteCmd(CMD_AP_KICKUSER);
			SendToClient(player, wpk);
			//踢人成功
			LogLine l_line(g_LogGrpServer);
			l_line << newln << "recieved killed acctname:[" << player->m_acctname << "] command!" << endln;
		}
		// 删除列表
		m_LoginList.Remove(player->m_acctname);
		player->Free();
	} else {
		l.unlock();
		LogLine l_line(g_LogGrpServer);
		l_line << newln << "recieved kill acctname:[" << accoutName << "] command(not in play list)!";
	}
}

void GroupServerApp::AP_KICKUSER(DataSocket* datasock, RPacket& pk) {
	Player* player{nullptr};
	uLong l_acctid = pk.ReadLong();
	RunChainGetArmor<Player> l(m_plylst);
	for (player = m_plylst.GetNextItem(); player; player = m_plylst.GetNextItem()) {
		if (player->m_acctLoginID == l_acctid) {
			break;
		}
	}
	if (player) {
		player->EndPlay(datasock);
		if (player->EndRun()) {
			if (player->m_currcha != -1) {
				//向AccountServer发送结束计费命令
				WPacket wpk = GetWPacket();
				wpk.WriteCmd(CMD_PA_USER_BILLEND);
				wpk.WriteString(player->m_acctname.c_str());
				SendData(m_acctsock, wpk);
			}
			//向AccountServer发送LogOut命令
			WPacket wpk = GetWPacket();
			wpk.WriteCmd(CMD_PA_USER_LOGOUT);
			wpk.WriteLong(player->m_acctid);
			wpk.WriteLong(player->m_sessid);
			SendData(m_acctsock, wpk);
			//向GateServer发送踢人命令
			/*WPacket */ wpk = GetWPacket();
			wpk.WriteCmd(CMD_AP_KICKUSER);
			SendToClient(player, wpk);
			//踢人成功
			LogLine l_line(g_LogGrpServer);
			l_line << newln << "recieved killed acctid/acctname:[" << player->m_acctid << "]/[" << player->m_acctname << "] command!" << endln;
		}
		// 删除列表
		m_LoginList.Remove(player->m_acctname);
		player->Free();
	} else {
		l.unlock();
		LogLine l_line(g_LogGrpServer);
		l_line << newln << "recieved kill acctid:[" << l_acctid << "] command(not in play list)!";
	}
}

void GroupServerApp::AP_EXPSCALE(DataSocket* datasock, RPacket& pk) {
	//  防沉迷
	Player* player{nullptr};
	const unsigned long ulChaID = pk.ReadLong();
	const unsigned long ulTime = pk.ReadLong();

	RunChainGetArmor<Player> l(m_plylst);
	for (player = m_plylst.GetNextItem(); player; player = m_plylst.GetNextItem()) {
		if (player->m_acctLoginID == ulChaID) {
			break;
		}
	}

	if (player) {
		WPacket wpk = GetWPacket();
		wpk.WriteCmd(CMD_PM_EXPSCALE);
		wpk.WriteLong(player->m_chaid[player->m_currcha]);
		wpk.WriteLong(ulTime);

		//player->m_gate->GetDataSock()->SendData(wpk);
		SendToClient(player, wpk);
	}
}

void GroupServerApp::TP_DISC(DataSocket* datasock, RPacket& pk) {
	uLong l_actid = pk.ReadLong();
	in_addr l_ina;
	l_ina.S_un.S_addr = pk.ReadLong();
	const char* l_reason = pk.ReadString();
	MutexArmor l_lockDB(m_mtxDB);
	m_tblaccounts->SetDiscInfo(l_actid, inet_ntoa(l_ina), l_reason);
	l_lockDB.unlock();
}

void GroupServerApp::TP_ESTOPUSER_CHECK(DataSocket* datasock, RPacket& pk) {
	Player* player{nullptr};
	const unsigned long l_acctid = pk.ReadLong();
	RunChainGetArmor<Player> l(m_plylst);
	for (player = m_plylst.GetNextItem(); player; player = m_plylst.GetNextItem()) {
		if (player->m_acctid == l_acctid) {
			break;
		}
	}
	if (player) {
		player->IsEstop();
	}
}

WPacket GroupServerApp::TP_USER_LOGOUT(Player* ply, DataSocket* datasock, RPacket& pk) {
	WPacket l_retpk = GetWPacket();
	if (!ply || !ply->m_gtAddr) {
		l_retpk.WriteShort(ERR_PT_INERR);
		return l_retpk;
	}

	uLong l_acctid = ply->m_acctid;
	if (!l_acctid || l_acctid != ply->m_acctid) {
		l_retpk.WriteShort(ERR_PT_INERR);
		return l_retpk;
	}
	RunChainGetArmor<Player> l(m_plylst);

	ply->EndPlay(datasock);

	if (ply->EndRun()) {
		if (ply->m_currcha != -1) {
			//发送结束计费命令
			WPacket wpk = GetWPacket();
			wpk.WriteCmd(CMD_PA_USER_BILLEND);
			wpk.WriteString(ply->m_acctname.c_str());
			SendData(m_acctsock, wpk);
		}

		//向AccountServer发送LogOut命令
		WPacket wpk = GetWPacket();
		wpk.WriteCmd(CMD_PA_USER_LOGOUT);
		wpk.WriteLong(ply->m_acctLoginID);
		wpk.WriteLong(ply->m_sessid);
		SendData(m_acctsock, wpk);
		//登出成功
		LogLine l_line(g_LogGrpServer);
		l_line << newln << "(" << ply->m_clientip << "):[" << ply->m_acctname << "]logout,\t online/total:" << m_plylst.GetTotal() << "/" << long(m_curChaNum);
	} else {
		LogLine l_line(g_LogGrpServer);
		l_line << newln << "(" << ply->m_clientip << "):[" << ply->m_acctname << "]logout,\t online/total:" << m_plylst.GetTotal() << "/" << long(m_curChaNum);
	}

	if (ply->m_bWG) {
		m_curWGChaNum--;
	}

	// 删除列表
	m_LoginList.Remove(ply->m_acctname);
	ply->Free();
	l.unlock();
	//返回成功错误码
	l_retpk.WriteShort(ERR_SUCCESS);
	return l_retpk;
}

WPacket GroupServerApp::TP_BGNPLAY(Player* ply, DataSocket* datasock, RPacket& pk) {
	WPacket retpk = GetWPacket();
	if (ply->m_currcha >= 0) {
		retpk.WriteShort(ERR_PT_INERR); //应该日值的内部错误
		return retpk;
	}

	unsigned short l_len;
	const char* l_cha = pk.ReadString(&l_len);
	if (!l_cha || l_len > CommConstants::Character::name_max_length) {
		retpk.WriteShort(ERR_PT_INERR); //应该日值的内部错误
		return retpk;
	}

	MutexArmor l_lockCha(ply->m_mtxCha);
	ply->m_bp_currcha = ply->FindIndexByChaName(l_cha);
	if (ply->m_bp_currcha < 0) { //本帐号没有这个角色
		retpk.WriteShort(ERR_PT_INVALIDCHA);
		return retpk;
	}
	if (ply->m_password.length() <= 0) {
		retpk.WriteShort(ERR_PT_INVALID_PW2);
		return retpk;
	}
	//合法角色
	MutexArmor l_lockDB(m_mtxDB);
	if (m_tblcharaters->FetchRowByChaID(ply->m_chaid[ply->m_bp_currcha]) < 1) {
		retpk.WriteShort(ERR_PT_INERR);
		return retpk;
	}

	const int l_maxval = atoi(m_cfg["Database"]["MaxVal"]);
	if (l_maxval && (m_tblcharaters->GetStr() > l_maxval ||
					 m_tblcharaters->GetDex() > l_maxval ||
					 m_tblcharaters->GetAgi() > l_maxval ||
					 m_tblcharaters->GetCon() > l_maxval ||
					 m_tblcharaters->GetSta() > l_maxval ||
					 m_tblcharaters->GetLuk() > l_maxval)) {
		retpk.WriteShort(ERR_PT_BADBOY);
		WPacket wpk = GetWPacket();
		wpk.WriteCmd(CMD_MC_SYSINFO);
		char l_buf[256];
		CFormatParameter param(2);
		param.setString(0, ply->m_acctname.c_str());
		param.setString(1, ply->m_chaname[ply->m_bp_currcha].c_str());
		RES_FORMAT_STRING(GP_GROUPSERVERAPPSERV_CPP_00002, param, l_buf);
		wpk.WriteString(l_buf);

		Player* playerlst[10240];
		short playernum = 0;

		RunChainGetArmor<Player> l(m_plylst);
		for (Player* playerr = m_plylst.GetNextItem(); playerr; playerr = m_plylst.GetNextItem()) {
			if (playerr->m_bp_currcha < 0) {
				continue;
			}
			playerlst[playernum] = playerr;
			playernum++;
		}
		l.unlock();
		SendToClient(playerlst, playernum, wpk);
		ply->m_currcha = -1;
		return retpk;
	}

	//返回成功相关信息
	retpk.WriteShort(ERR_SUCCESS); //选角色成功返回
	retpk.WriteString(ply->m_password.c_str());
	retpk.WriteLong(ply->m_chaid[ply->m_bp_currcha]); //角色ID
	retpk.WriteLong(ply->m_chaid[ply->m_bp_currcha]); //WorldID
	retpk.WriteString(m_tblcharaters->GetMap());	  //上次下线的地图名
	short swiner = 0;
	for (int i = 0; i < MAXORDERNUM; i++) {
		if (ply->m_chaid[ply->m_bp_currcha] == m_tbLparam->GetOrderData(i)->nid) {
			swiner = i + 1;
			break;
		}
	}
	retpk.WriteShort(swiner);
	LogLine l_line(g_LogGrpServer);
	l_line << newln << "(" << ply->m_clientip << "):[" << ply->m_acctname << "]select char[" << l_cha
		   << "]begin play...，\t online/total:" << m_plylst.GetTotal() << "/"
		   << long(m_curChaNum);

	return retpk;
}

WPacket GroupServerApp::TP_ENDPLAY(Player* ply, DataSocket* datasock, RPacket& pk) {
	WPacket l_retpk = GetWPacket();
	if (ply->m_currcha < 0) {
		l_retpk.WriteShort(ERR_PT_INERR); //应该日值的系统不一致错误
	} else {
		l_retpk.WriteShort(ERR_SUCCESS); //重选角色成功返回
		ply->EndPlay(datasock);

		LogLine l_line(g_LogGrpServer);
		l_line << newln << "(" << ply->m_clientip << "):[" << ply->m_acctname << "]exit char["
			   << ply->m_chaname[ply->m_currcha] << "]begin entry select char UI...，\t online/total:"
			   << m_plylst.GetTotal() << "/" << long(m_curChaNum);
		l_line << endln;

		ply->m_currcha = -1; //置为无效的当前角色
		ply->EndPlayReset();
		//发送结束计费命令
		WPacket wpk = GetWPacket();
		wpk.WriteCmd(CMD_PA_USER_BILLEND);
		wpk.WriteString(ply->m_acctname.c_str());
		SendData(m_acctsock, wpk);

		//从数据库里面取出角色表
		GetCHAsFromDBByPlayer(ply, l_retpk);
	}
	return l_retpk;
}

void GroupServerApp::MP_ENTERMAP(Player* ply, DataSocket* datasock, RPacket& pk) {
	const auto l_isSwitch = static_cast<bool>(pk.ReadChar());
	if (!l_isSwitch && ply->m_currcha < 0) {
		MP_ONLINE(ply);
	} else if (l_isSwitch && ply->m_currcha >= 0) {
		MP_SWITCH(ply);
	}
}

void GroupServerApp::MP_ONLINE(Player* ply) {
	MutexArmor l_lockDB(m_mtxDB);
	ply->m_currcha = ply->m_bp_currcha;
	ply->m_bp_currcha = -1;
	m_tblcharaters->SetAddr(ply->m_chaid[ply->m_currcha], ToAddress(ply));
	++m_curChaNum;
	LogLine l_line(g_LogGrpServer);
	l_line << newln << "(" << ply->m_clientip << "):[" << ply->m_acctname << "] char ["
		   << ply->m_chaname[ply->m_currcha] << "]entry map server begin play...，\t online/total:"
		   << m_plylst.GetTotal() << "/" << long(m_curChaNum);
	l_line << endln;

	//发送开始计费命令
	WPacket wpk = GetWPacket();
	wpk.WriteCmd(CMD_PA_USER_BILLBGN);
	wpk.WriteString(ply->m_acctname.c_str());
	wpk.WriteString(ply->m_passport.c_str());
	SendData(m_acctsock, wpk);

	ply->CheckEstop();

	PC_FRND_INIT(ply);
	PC_GULD_INIT(ply);
	PC_MASTER_INIT(ply);
}

WPacket GroupServerApp::TP_NEWCHA(Player* ply, DataSocket* datasock, RPacket& pk) {
	WPacket l_retpk = GetWPacket();
	if (ply->m_currcha >= 0) {
		l_retpk.WriteShort(ERR_PT_INERR); //应该日值的系统不一致错误
		return l_retpk;
	}
	MutexArmor l_lockCha(ply->m_mtxCha);
	if (ply->m_chanum >= const_cha.MaxChaNum) { //已达到系统限制最大角色数
		l_retpk.WriteShort(ERR_PT_TOMAXCHA);
		return l_retpk;
	}
	unsigned short l_len;
	const char* l_chaname = pk.ReadString(&l_len);
	if (!l_chaname) {
		l_retpk.WriteShort(ERR_PT_INERR);
		return l_retpk;
	} else if (l_len > CommConstants::Character::name_max_length) {
		l_retpk.WriteShort(ERR_PT_TOOBIGCHANM);
		return l_retpk;
	} else if (!IsValidName(l_chaname, l_len) || !CTextFilter::IsLegalText(CTextFilter::NAME_TABLE, l_chaname)) { //(strchr(l_chaname,'\''))//角色名中不能有单引号'
		l_retpk.WriteShort(ERR_PT_ERRCHANAME);																	  //角色名不合法
		return l_retpk;
	}
	//cChar	*	l_birth			=pk.ReadString(&l_len);
	//dstring		l_birth1	="";
	//cChar	*	l_birth2		=0;
	//if(l_birth && l_len <30 && !strchr(l_birth,'/'))
	//{
	//	l_birth1	=dstring("/")<<l_birth<<"/";

	//	try{
	//		l_birth2		=this->m_cfg["角色"]["出生地"];
	//	}catch(...)
	//	{
	//		l_birth2		=0;
	//	}
	//}else
	//{
	//	l_birth2	=0;
	//}
	//if(!l_birth2 ||!strstr(l_birth2,l_birth1))
	//{
	//	l_retpk.WriteShort(ERR_PT_INVALIDBIRTH);		//出生地非法
	//}else
	//{
	const char* l_birth = pk.ReadString(&l_len);
	dstring l_birth1 = "";
	const char* l_map{nullptr};
	LG("Newcha", "Probable new cha name: %s\n", l_birth);
	if (l_birth && l_len < 30 && !strchr(l_birth, '/')) {
		l_birth1 = l_birth;
		try {
			// Modify by lark.li 20080702 begin
			//l_map	=m_cfg["出生地"][l_birth];
			//l_map	=m_cfg["birthplace"][l_birth];
			std::map<std::string, std::string>::iterator it = m_mapBirthplace.find(std::string(l_birth));
			printf("%s\n", it);

			if (it != m_mapBirthplace.end()) {
				l_map = it->second.c_str();
			}

			// End
		} catch (...) {
			l_map = nullptr;
		}
	} else {
		l_map = nullptr;
	}
	if (!l_map) {
		l_retpk.WriteShort(ERR_PT_INVALIDBIRTH); //出生地非法
		return l_retpk;
	}
	const LOOK* look = reinterpret_cast<const LOOK*>(pk.ReadSequence(l_len));
	if (!look || l_len != sizeof(LOOK)) {
		l_retpk.WriteShort(ERR_PT_INVALIDDAT);
		return l_retpk;
	}
	char l_look[defLOOK_DATA_STRING_LEN];
	try {
		if (!LookData2String(look, l_look, defLOOK_DATA_STRING_LEN)) {
			l_retpk.WriteShort(ERR_PT_INVALIDDAT);
			return l_retpk;
		}
	} catch (...) {
		LogLine l_line(g_LogGrpServer);
		l_line << newln << "account[" << ply->m_acctname << "]new char[" << l_chaname << "]find appreance data convert exception" << endln;
		l_retpk.WriteShort(ERR_PT_INVALIDDAT);
		return l_retpk;
	}
	MutexArmor l_lockDB(m_mtxDB);
	if (!m_tblcharaters->InsertRow(l_chaname, ply->m_acctid, l_birth, l_map, l_look)) { //角色名重复
		LogLine l_line(g_LogGrpServer);
		l_line << newln << "account[" << ply->m_acctname << "]new char[" << l_chaname << "]the same name exception" << endln;
		l_retpk.WriteShort(ERR_PT_SAMECHANAME);
		return l_retpk;
	}
	l_retpk.WriteShort(ERR_SUCCESS);
	//更新数据库中帐号的角色ID列表CharIDs
	if (m_tblcharaters->FetchRowByChaName(l_chaname) < 1) {
		l_retpk.WriteShort(ERR_PT_INERR);
		LogLine l_line(g_LogGrpServer);
		l_line << newln << "account[" << ply->m_acctname << "] when create char , can't restore database failed.";
		return l_retpk;
	}
	ply->m_chaid[ply->m_chanum] = m_tblcharaters->Getcha_id();
	ply->m_chaname[ply->m_chanum] = l_chaname;
	ply->m_motto[ply->m_chanum] = m_tblcharaters->GetMottonByName();
	ply->m_icon[ply->m_chanum] = m_tblcharaters->GetIconByName();
	ply->m_guild[ply->m_chanum] = 0;
	ply->m_chanum++;

	char l_CharIDs[80];
	l_CharIDs[0] = 0;
	char l_buf[20];
	for (char i = 0; i < ply->m_chanum; i++) {
		_itoa_s(ply->m_chaid[i], l_buf, sizeof(l_buf), 10);
		strncat_s(l_CharIDs, sizeof(l_CharIDs), l_buf, _TRUNCATE);
		strncat_s(l_CharIDs, sizeof(l_CharIDs), ";", _TRUNCATE);
	}
	m_tblaccounts->UpdateRow(ply->m_acctid, l_CharIDs);
	l_lockDB.unlock();
	LogLine l_line(g_LogGrpServer);
	l_line << newln << "(" << ply->m_clientip << "):[" << ply->m_acctname << "]create char ["
		   << l_chaname << "]，\t online/total:"
		   << m_plylst.GetTotal() << "/" << long(m_curChaNum) << endln;
	l_lockCha.unlock();
	return l_retpk;
}

WPacket GroupServerApp::TP_DELCHA(Player* ply, DataSocket* datasock, RPacket& pk) {
	WPacket retpk = GetWPacket();
	if (ply->m_currcha >= 0) {
		retpk.WriteShort(ERR_PT_INERR); //应该日值的系统不一致错误
		return retpk;
	}

	unsigned short l_len, l_len2;
	const char* l_cha = pk.ReadString(&l_len);
	const char* l_pw2 = pk.ReadString(&l_len2);
	if (!l_cha || l_len > CommConstants::Character::name_max_length) {
		retpk.WriteShort(ERR_PT_INERR);
		return retpk;
	}
	if (strcmp(l_pw2, ply->m_password.c_str()) != 0) {
		retpk.WriteShort(ERR_PT_INVALID_PW2);
		return retpk;
	}

	MutexArmor l_lockCha(ply->m_mtxCha);
	char l_chaidx = ply->FindIndexByChaName(l_cha);
	if (l_chaidx < 0) { //本帐号没有这个角色
		retpk.WriteShort(ERR_PT_INVALIDCHA);
		return retpk;
	}
	if (FindGuildByLeadID(ply->m_chaid[l_chaidx])) { //合法的角色
		retpk.WriteShort(ERR_PT_ISGLDLEADER);
		return retpk;
	}
#ifdef SHUI_JING
	if (m_tblcrystal->IsHasBuyorSale(ply->m_chaid[l_chaidx], 0) ||
		m_tblcrystal->IsHasBuyorSale(ply->m_chaid[l_chaidx], 1)) {
		retpk.WriteShort(ERR_PT_HASCRYSTALTRADE);
		return retpk;
	}
#endif

	bool bFlag = false;
	const int l_chaid = ply->m_chaid[l_chaidx];
	char l_CharIDs[80];
	l_CharIDs[0] = 0;
	char l_buf[20];
	for (char i = 0; i < ply->m_chanum; i++) {
		if (i == l_chaidx) {
			continue;
		}
		_itoa_s(ply->m_chaid[i], l_buf, sizeof(l_buf), 10);
		strncat_s(l_CharIDs, sizeof(l_CharIDs), l_buf, _TRUNCATE);
		strncat_s(l_CharIDs, sizeof(l_CharIDs), ";", _TRUNCATE);
	}

	MutexArmor l_lockDB(m_mtxDB);
	// 判断角色是否公会成员，否则删除公会列表信息
	if (m_tblaccounts->begin_tran()) {
		if (!m_tblaccounts->UpdateRow(ply->m_acctid, l_CharIDs) || !m_tblcharaters->BackupRow(l_chaid) || !m_tblaccounts->commit_tran()) {
			m_tblaccounts->rollback();
		} else {
			bFlag = true;
		}
	}
	l_lockDB.unlock();

	if (bFlag) {
		retpk.WriteShort(ERR_SUCCESS); //删除角色成功返回
		ply->m_chanum--;
		for (; l_chaidx < ply->m_chanum; l_chaidx++) {
			ply->m_chaid[l_chaidx] = ply->m_chaid[l_chaidx + 1];
			ply->m_chaname[l_chaidx] = ply->m_chaname[l_chaidx + 1];
			ply->m_motto[l_chaidx] = ply->m_motto[l_chaidx + 1];
			ply->m_icon[l_chaidx] = ply->m_icon[l_chaidx + 1];
			ply->m_guild[l_chaidx] = ply->m_guild[l_chaidx + 1];
		}

		LogLine l_line(g_LogGrpServer);
		l_line << newln << "(" << ply->m_clientip << "):[" << ply->m_acctname << RES_STRING(GP_GROUPSERVERAPPSERV_CPP_00043)
			   << l_cha << RES_STRING(GP_GROUPSERVERAPPSERV_CPP_00044) << m_plylst.GetTotal() << "/" << long(m_curChaNum)
			   << endln;
	} else {
		retpk.WriteShort(ERR_PT_SERVERBUSY); //服务器忙碌，请稍后
		LogLine l_line(g_LogGrpServer);
		l_line << newln << "(" << ply->m_clientip << "):[" << ply->m_acctname << "]delete char failed["
			   << l_cha << "]，\t GetTotal/m_curChaNum:" << m_plylst.GetTotal() << "/" << long(m_curChaNum)
			   << endln;
	}
	return retpk;
}

WPacket GroupServerApp::TP_CREATE_PASSWORD2(Player* ply, DataSocket* datasock, RPacket& pk) {
	WPacket l_retpk = GetWPacket();
	const std::string strPassword = pk.ReadString();

	if (ply->m_password.empty() && strPassword.length() <= ROLE_MAXSIZE_PASSWORD2) {
		MutexArmor l_lockDB(m_mtxDB);

		if (m_tblaccounts->UpdatePassword(ply->m_acctid, strPassword.c_str())) {
			ply->m_password = strPassword;
			l_retpk.WriteShort(ERR_SUCCESS);
			LogLine l_line(g_LogErrServer);
			l_line << newln << "account:" << ply->m_acctname << "ID:" << ply->m_acctid << "database operate success:(" << strPassword.c_str() << ")" << endln;
		} else {
			l_retpk.WriteShort(ERR_PT_SERVERBUSY);
			LogLine l_line(g_LogErrServer);
			l_line << newln << "account:" << ply->m_acctname << "ID:" << ply->m_acctid << "database operate failed:(" << strPassword.c_str() << ")" << endln;
		}
	} else {
		l_retpk.WriteShort(ERR_PT_INVALID_PW2);
		LogLine l_line(g_LogErrServer);
		l_line << newln << "account:" << ply->m_acctname << "ID:" << ply->m_acctid << "wrong second password:(" << strPassword.c_str() << ")" << endln;
	}
	return l_retpk;
}

WPacket GroupServerApp::TP_UPDATE_PASSWORD2(Player* ply, DataSocket* datasock, RPacket& pk) {
	WPacket l_retpk = GetWPacket();
	const std::string strOld = pk.ReadString();
	const std::string strPassword = pk.ReadString();

	if (ply->m_password == strOld && strPassword.length() <= ROLE_MAXSIZE_PASSWORD2) {
		MutexArmor l_lockDB(m_mtxDB);

		if (m_tblaccounts->UpdatePassword(ply->m_acctid, strPassword.c_str())) {
			ply->m_password = strPassword;
			l_retpk.WriteShort(ERR_SUCCESS);
		} else {
			l_retpk.WriteShort(ERR_PT_SERVERBUSY);
		}
	} else {
		l_retpk.WriteShort(ERR_PT_INVALID_PW2);
	}
	return l_retpk;
}

/*						char *l_str	=strstr(l_look,";");
						if(l_str)	*l_str=0;
						look.sTypeID	=atoi(l_look);
						l_look	=l_str+1;
						l_str	=strstr(l_look,";");
						for(int i=0;(l_str ||*l_look)&&(i<enumEQUIP_NUM);i++)
						{
							if(l_str)	*l_str=0;
							look.chState[i]	=atoi(l_look);
							if(l_str)
							{
								l_look	=l_str+1;
								l_str	=strstr(l_look,";");
							}else
							{
								l_look --;
							}
						}
						for(int i=0;(l_str ||*l_look)&&(i<enumEQUIP_NUM);i++)
						{
							if(l_str)	*l_str=0;
							look.sLink[i]	=atoi(l_look);
							if(l_str)
							{
								l_look	=l_str+1;
								l_str	=strstr(l_look,";");
							}else
							{
								l_look --;
							}
						}
*/
/*							char	l_tmpbuf[20];
							strcpy(l_look,itoa(look->sTypeID,l_tmpbuf,10));
							for(short i=0;i<enumEQUIP_NUM;i++)
							{
								strcat(l_look,";");
								strcat(l_look,itoa(look->chState[i],l_tmpbuf,10));
							}
							for(short i=0;i<enumEQUIP_NUM;i++)
							{
								strcat(l_look,";");
								strcat(l_look,itoa(look->sLink[i],l_tmpbuf,10));
							}
*/

void GroupServerApp::MP_GARNER2_UPDATE(Player* ply, DataSocket* datasock, RPacket& pk) {
	ORDERINFO orderinfo;
	//SYSTEMTIME st;time_t
	//GetLocalTime( &st);
	//time_t tt;
	//time(&tt);
	orderinfo.nid = pk.ReadLong();
	const std::string strChaName = pk.ReadString();
	orderinfo.nlev = pk.ReadLong();
	const std::string strjob = pk.ReadString();
	const short sFightpoint = pk.ReadShort();

	if (strChaName.length() > 20) {
		LogLine l_line(g_LogGarner2);
		l_line << newln << "order data exception";
		return;
	}
	strncpy_s(orderinfo.strname, sizeof(orderinfo.strname), strChaName.c_str(), _TRUNCATE);

	if (strjob.length() > 100) {
		LogLine l_line(g_LogGarner2);
		l_line << newln << "order data exception";
		return;
	}
	strncpy_s(orderinfo.strjob, sizeof(orderinfo.strjob), strjob.c_str(), _TRUNCATE);
	orderinfo.nfightpoint = (long)sFightpoint;

	MutexArmor l_lockDB(m_mtxDB);
	m_tbLparam->UpdateOrder(orderinfo);
	CP_GARNER2_GETORDER(ply, datasock, pk);
}

void GroupServerApp::CP_GARNER2_GETORDER(Player* ply, DataSocket* datasock, RPacket& pk) {
	WPacket wpk = g_gpsvr->GetWPacket();
	wpk.WriteCmd(CMD_PC_GARNER2_ORDER);
	for (int i = 0; i < MAXORDERNUM; i++) {
		ORDERINFO* porder = m_tbLparam->GetOrderData(i);
		wpk.WriteString(porder->strname);
		wpk.WriteLong(porder->nlev);
		wpk.WriteString(porder->strjob);
		wpk.WriteLong(porder->nfightpoint);
	}
	g_gpsvr->SendToClient(ply, wpk);
}

void GroupServerApp::MP_GM_BANACCOUNT(Player* ply, DataSocket* datasock, RPacket& pk) {
	const std::string actName = pk.ReadString();
	WPacket wpk = g_gpsvr->GetWPacket();
	wpk.WriteCmd(CMD_PA_GMBANACCOUNT);
	wpk.WriteString(actName.c_str());
	g_gpsvr->SendData(g_gpsvr->m_acctsock, wpk);
}
