/* Generated by Together */

#include "excp.h"
#include "DataSocket.h"
#include "GroupServerApp.h"
#include "Player.h"
#include "Team.h"
#include "GameCommon.h"

_DBC_USING

Player::Player(size_t size)
	: PreAllocStru(size) {
	m_mtxCha.Create(false);
}

Player::~Player() {}

void Player::Initially() {
	RunBiDirectItem<Player>::Initially();
	GuildMember::Initially();
	TeamMember::Initially();
	//ToDo:Self's Init Operation

	m_lastip[0] = 1;
	m_lastreason[0] = 1;
	m_lastleavetime[0] = 1;
	m_pingply = nullptr;

	m_gm = 0;
	m_gate = nullptr;
	m_gtAddr = 0;
	m_bp_currcha = -1;
	m_currcha = -1;
	m_chanum = 0;
	m_acctid = 0;
	m_acctLoginID = 0;
	m_acctname = "";
	m_chatnum = 0;
	m_chatarranum = 0;

	m_bWG = false;

	m_lChatMoney = 1000;
	m_lTradeChatMoney = 1000;
	m_bNew = false;

	EndPlayReset();
}

void Player::Finally() {
	m_gate = nullptr;
	m_gtAddr = 0;
	m_bp_currcha = -1;
	m_currcha = -1;
	m_chanum = 0;
	m_acctid = 0;
	m_acctLoginID = 0;
	m_acctname = "";
	m_chatnum = 0;
	m_chatarranum = 0;

	m_lChatMoney = 1000;
	m_lTradeChatMoney = 1000;
	m_bNew = false;

	//-----------
	TeamMember::Finally();
	GuildMember::Finally();
	RunBiDirectItem<Player>::Finally();
}

bool Player::BeginRun() {
	return RunBiDirectItem<Player>::_BeginRun(&(g_gpsvr->m_plylst)) ? true : false;
}

bool Player::EndRun() {
	return RunBiDirectItem<Player>::_EndRun() ? true : false;
}

void Player::EndPlay(DataSocket* datasock) {
	if (m_currcha >= 0) {
		//g_gpsvr->DelPlayerFromList(m_chaid[m_currcha]);

		CountEstopTime();
		if (GetTeam()) {
			RPacket l_rpk1;
			g_gpsvr->CP_TEAM_LEAVE(this, datasock, l_rpk1);
		}
		if (m_chatarranum) {
			WPacket wpk1 = g_gpsvr->GetWPacket();
			MutexArmor selock(m_mtxChat);
			while (m_chatarranum) {
				WPacket wpk2 = wpk1;
				wpk2.WriteLong(m_chat[0]->GetSession()->GetID());
				RPacket rpk = RPacket(rpk);
				g_gpsvr->CP_SESS_LEAVE(this, datasock, rpk);
			}
			selock.unlock();
		}
		if (GetGuild()) {
			WPacket l_toGuild = g_gpsvr->GetWPacket();
			l_toGuild.WriteCmd(CMD_PC_GUILD);
			l_toGuild.WriteChar(MSG_GUILD_OFFLINE);
			l_toGuild.WriteLong(m_chaid[m_currcha]);

			Player* playerlst[10240];
			short playernum = 0;

			RunChainGetArmor<GuildMember> l(*GetGuild());
			Player* player;
			while (player = static_cast<Player*>(GetGuild()->GetNextItem())) {
				if (player != this) {
					playerlst[playernum] = player;
					playernum++;
				}
			}
			l.unlock();
			g_gpsvr->SendToClient(playerlst, playernum, l_toGuild);
			LeaveGuild();
		}
		{
			MutexArmor l_lockDB(g_gpsvr->m_mtxDB);
			g_gpsvr->m_tblcharaters->SetAddr(m_chaid[m_currcha], 0);
			--(g_gpsvr->m_curChaNum);

			//好友下线通知
			{
				friend_dat l_farray[200];
				int l_num = 200;
				g_gpsvr->m_tblX1->get_friend_dat(l_farray, l_num, m_chaid[m_currcha]);

				WPacket l_toFrnd = g_gpsvr->GetWPacket();
				l_toFrnd.WriteCmd(CMD_PC_FRND_REFRESH);
				l_toFrnd.WriteChar(MSG_FRND_REFRESH_OFFLINE);
				l_toFrnd.WriteLong(m_chaid[m_currcha]);

				Player* playerlst[10240];
				short playernum = 0;

				Player* player1;
				char l_currcha;
				for (int i = 0; i < l_num; i++) {
					if (l_farray[i].cha_id && (player1 = ToPointer<Player>(l_farray[i].memaddr)) && ((l_currcha = player1->m_currcha) >= 0) && (player1->m_chaid[l_currcha] == l_farray[i].cha_id)) {
						playerlst[playernum] = player1;
						playernum++;
					}
				}
				g_gpsvr->SendToClient(playerlst, playernum, l_toFrnd);
			}

			//学徒下线通知
			{
				TBLMaster::master_dat l_farray[200];
				int l_num = 200;
				g_gpsvr->m_tblmaster->GetMasterData(l_farray, l_num, m_chaid[m_currcha]);

				WPacket l_toFrnd = g_gpsvr->GetWPacket();
				l_toFrnd.WriteCmd(CMD_PC_MASTER_REFRESH);
				l_toFrnd.WriteChar(MSG_PRENTICE_REFRESH_OFFLINE);
				l_toFrnd.WriteLong(m_chaid[m_currcha]);

				Player* playerlst[10240];
				short playernum = 0;

				Player* player1;
				char l_currcha;
				for (int i = 0; i < l_num; i++) {
					if (l_farray[i].cha_id && (player1 = ToPointer<Player>(l_farray[i].memaddr)) && ((l_currcha = player1->m_currcha) >= 0) && (player1->m_chaid[l_currcha] == l_farray[i].cha_id)) {
						playerlst[playernum] = player1;
						playernum++;
					}
				}
				g_gpsvr->SendToClient(playerlst, playernum, l_toFrnd);
				m_CurrMasterNum = 0;
			}

			//导师下线通知
			{
				TBLMaster::master_dat l_farray[200];
				int l_num = 200;
				g_gpsvr->m_tblmaster->GetPrenticeData(l_farray, l_num, m_chaid[m_currcha]);

				WPacket l_toFrnd = g_gpsvr->GetWPacket();
				l_toFrnd.WriteCmd(CMD_PC_MASTER_REFRESH);
				l_toFrnd.WriteChar(MSG_MASTER_REFRESH_OFFLINE);
				l_toFrnd.WriteLong(m_chaid[m_currcha]);

				Player* playerlst[10240];
				short playernum = 0;

				Player* player1;
				char l_currcha;
				for (int i = 0; i < l_num; i++) {
					if (l_farray[i].cha_id && (player1 = ToPointer<Player>(l_farray[i].memaddr)) && ((l_currcha = player1->m_currcha) >= 0) && (player1->m_chaid[l_currcha] == l_farray[i].cha_id)) {
						playerlst[playernum] = player1;
						playernum++;
					}
				}
				g_gpsvr->SendToClient(playerlst, playernum, l_toFrnd);
				m_CurrPrenticeNum = 0;
			}

			l_lockDB.unlock();
		}
	}
}

void Player::EndPlayReset() {
	m_refuse_tome = false;
	m_refuse_sess = false;
	m_worldtick = 0;
	m_tradetick = 0;
	m_worldticktemp = 0;
	m_tradeticktemp = 0;
	m_toyoutick = 0;
}

char Player::FindIndexByChaName(cChar* chaname) {
	if (!chaname) {
		return -1;
	}
	char i = 0;
	for (i = 0; i < m_chanum; i++) {
		if (m_chaname[i] == chaname) {
			break;
		}
	}
	if (i < m_chanum) {
		{
			return i;
		}
	} else {
		return -1;
	}
}
void Player::SendSysInfo(cChar* info) {
	if (m_currcha < 0 || !m_gate || !m_gate->GetDataSock()) {
		return;
	}
	WPacket wpk = m_gate->GetDataSock()->GetWPacket();
	wpk.WriteCmd(CMD_MC_SYSINFO);
	wpk.WriteString(info);
	g_gpsvr->SendToClient(this, wpk);
}

extern BOOL GetOnlineCount(DWORD& dwLoginNum, DWORD& dwPlayerNum);

void Player::DoCommand(cChar* cmd) {
	if ((strcmp(cmd, "getlastconnection") == 0) &&
		PrivilegeCheck::Instance()->HasPrivilege(this->m_gm, "getlastconnection")) {
		MutexArmor l_lockDB(g_gpsvr->m_mtxDB);
		if (m_lastip[0] == 1) {
			g_gpsvr->m_tblaccounts->FetchRowByActID(m_acctid);
			strncpy_s(m_lastip, sizeof(m_lastip), g_gpsvr->m_tblaccounts->GetLast_IP(), _TRUNCATE);
			strncpy_s(m_lastreason, sizeof(m_lastreason), g_gpsvr->m_tblaccounts->GetDisc_Reason(), _TRUNCATE);
			strncpy_s(m_lastleavetime, sizeof(m_lastleavetime), g_gpsvr->m_tblaccounts->GetLast_Leave(), _TRUNCATE);
		}
		l_lockDB.unlock();
		char l_buf[512];
		CFormatParameter param(3);
		param.setString(0, m_lastip);
		param.setString(1, m_lastleavetime);
		param.setString(2, m_lastreason);
		RES_FORMAT_STRING(GP_PLAYER_CPP_00001, param, l_buf);
		SendSysInfo(l_buf);
	} else if ((strncmp(cmd, "getuserconnection ", strlen("getuserconnection ") == 0)) &&
			   PrivilegeCheck::Instance()->HasPrivilege(this->m_gm, "getuserconnection")) {
		Player* player = g_gpsvr->FindPlayerByChaName(cmd + strlen("getuserconnection "));
		if (!player) {
			char l_buf[512];
			_snprintf_s(l_buf, sizeof(l_buf), _TRUNCATE, RES_STRING(GP_PLAYER_CPP_00002), cmd + strlen("getuserconnection "));
			SendSysInfo(l_buf);
		} else {
			MutexArmor l_lockDB(g_gpsvr->m_mtxDB);
			if (player->m_lastip[0] == 1) {
				g_gpsvr->m_tblaccounts->FetchRowByActID(player->m_acctid);
				strncpy_s(player->m_lastip, sizeof(player->m_lastip), g_gpsvr->m_tblaccounts->GetLast_IP(), _TRUNCATE);
				strncpy_s(player->m_lastreason, sizeof(player->m_lastreason), g_gpsvr->m_tblaccounts->GetDisc_Reason(), _TRUNCATE);
				strncpy_s(player->m_lastleavetime, sizeof(player->m_lastleavetime), g_gpsvr->m_tblaccounts->GetLast_Leave(), _TRUNCATE);
			}
			l_lockDB.unlock();
			char l_buf[512];
			CFormatParameter param(4);
			param.setString(0, cmd + strlen("getuserconnection "));
			param.setString(1, player->m_lastip);
			param.setString(2, player->m_lastleavetime);
			param.setString(3, player->m_lastreason);
			RES_FORMAT_STRING(GP_PLAYER_CPP_00003, param, l_buf);
			SendSysInfo(l_buf);
		}
	} else if ((strcmp(cmd, "getusernum+") == 0) &&
			   PrivilegeCheck::Instance()->HasPrivilege(this->m_gm, "getusernum+")) {
		Player* player = g_gpsvr->FindPlayerByChaName(m_chaname[m_currcha].c_str());
		if (player) {
			if (player->m_gm > 0) {
				MutexArmor l_lockDB(g_gpsvr->m_mtxDB);
				DWORD dwLoginNum = DWORD(g_gpsvr->m_plylst.GetTotal());
				DWORD dwPlayerNum = DWORD(g_gpsvr->m_curChaNum);
				if (GetOnlineCount(dwLoginNum, dwPlayerNum)) {
					char l_buf[512];
					CFormatParameter param(2);
					param.setLong(0, dwLoginNum);
					param.setLong(1, dwPlayerNum);
					RES_FORMAT_STRING(GP_PLAYER_CPP_00004, param, l_buf);
					SendSysInfo(l_buf);
				}
			}
		}
	} else if ((strncmp(cmd, "ping ", strlen("ping ") == 0)) &&
			   PrivilegeCheck::Instance()->HasPrivilege(this->m_gm, "ping")) {
		Player* player = g_gpsvr->FindPlayerByChaName(cmd + strlen("ping "));
		if (!player) {
			char l_buf[512];
			_snprintf_s(l_buf, sizeof(l_buf), _TRUNCATE, RES_STRING(GP_PLAYER_CPP_00005), cmd + strlen("ping "));
			SendSysInfo(l_buf);
		} else {
			player->m_pingply = this;
			WPacket wpk = g_gpsvr->GetWPacket();
			wpk.WriteCmd(CMD_PC_PING);
			g_gpsvr->SendToClient(player, wpk);
		}
	} else if ((strncmp(cmd, "bbs ", strlen("bbs ") == 0)) &&
			   PrivilegeCheck::Instance()->HasPrivilege(this->m_gm, "bbs")) {
		const char* l_dim;
		const char* l_cmd = cmd + strlen("bbs ");
		l_dim = strchr(l_cmd, ',');
		if (!l_dim) {
			SendSysInfo(RES_STRING(GP_PLAYER_CPP_00006));
		}
		l_dim = nullptr;
		const unsigned long l_inter = atoi(l_cmd);
		if (!l_inter) {
			SendSysInfo(RES_STRING(GP_PLAYER_CPP_00007));
		}
		l_cmd = l_dim + 1;
		l_dim = strchr(l_cmd, ',');
		if (!l_dim) {
			SendSysInfo(RES_STRING(GP_PLAYER_CPP_00006));
		}
		l_dim = nullptr;
		const unsigned long l_times = atoi(l_cmd);
		if (!l_times) {
			SendSysInfo(RES_STRING(GP_PLAYER_CPP_00008));
		}
		l_cmd = l_dim + 1;
		if (!strlen(l_cmd)) {
			SendSysInfo(RES_STRING(GP_PLAYER_CPP_00009));
		}

		g_gmbbs->AddBBS(l_inter, l_times, l_cmd);

	} else if ((strncmp(cmd, "estop", strlen("estop") == 0)) &&
			   PrivilegeCheck::Instance()->HasPrivilege(this->m_gm, "estop")) {

		const char* l_cmd = cmd + strlen("estop");
		l_cmd = strchr(l_cmd, ' ');
		if (!l_cmd) {
			SendSysInfo(RES_STRING(GP_PLAYER_CPP_00012));
		}
		const char* playername = ++l_cmd;
		l_cmd = strchr(l_cmd, ',');
		if (!l_cmd) {
			SendSysInfo(RES_STRING(GP_PLAYER_CPP_00012));
		}
		l_cmd = nullptr;
		const unsigned long lTimes = atoi(++l_cmd);
		EstopPlayer(playername, lTimes);
	} else if ((strncmp(cmd, "delestop", strlen("delestop")) == 0) &&
			   PrivilegeCheck::Instance()->HasPrivilege(this->m_gm, "delestop")) {
		const char* l_cmd = cmd + strlen("estop");
		l_cmd = strchr(l_cmd, ' ');
		if (!l_cmd) {
			SendSysInfo(RES_STRING(GP_PLAYER_CPP_00013));
		}
		const char* playername = ++l_cmd;
		DelEstopPlayer(playername);
	} else if ((!strncmp(cmd, "disable", strlen("disable"))) &&
			   PrivilegeCheck::Instance()->HasPrivilege(this->m_gm, "disable")) {

		// 屏蔽该角色帐号
		const char* l_cmd = cmd + strlen("estop");
		l_cmd = strchr(l_cmd, ' ');
		if (!l_cmd) {
			SendSysInfo(RES_STRING(GP_PLAYER_CPP_00014));
		}
		const char* playername = ++l_cmd;
		l_cmd = strchr(l_cmd, ',');
		if (!l_cmd) {
			SendSysInfo(RES_STRING(GP_PLAYER_CPP_00014));
		}
		l_cmd = nullptr;
		const unsigned long lTimes = atoi(++l_cmd);
		DisablePlayer(playername, lTimes);
	} else {
		SendSysInfo(RES_STRING(GP_PLAYER_CPP_00015));
		return;
	}
}

bool Player::IsEstop() {
	if (!m_estop[m_currcha]) {
		return false;
	}
	const uLong l_curtick = g_gpsvr->GetCurrentTick();
	if (l_curtick - this->m_worldtick > 1000 * 60 * 2) {
		MutexArmor l_lockDB(g_gpsvr->m_mtxDB);
		if (!g_gpsvr->m_tblcharaters->IsEstop(m_chaid[m_currcha])) {
			// 发送解除命令
			WPacket wpk = g_gpsvr->GetWPacket();
			wpk.WriteCmd(CMD_PT_DEL_ESTOPUSER);
			g_gpsvr->SendToClient(this, wpk);

			SendSysInfo(RES_STRING(GP_PLAYER_CPP_00016));

			CountEstopTime();
			m_estop[m_currcha] = false;
			return false;
		} else {
			m_estop[m_currcha] = true;
			return true;
		}
	}
	return true;
}

void Player::CheckEstop() {
	MutexArmor l_lockDB(g_gpsvr->m_mtxDB);
	g_gpsvr->m_tblcharaters->StartEstopTime(m_chaid[m_currcha]);
	if (g_gpsvr->m_tblcharaters->IsEstop(m_chaid[m_currcha])) {
		// 发送禁言消息和命令
		WPacket wpk = g_gpsvr->GetWPacket();
		wpk.WriteCmd(CMD_PT_ESTOPUSER);
		g_gpsvr->SendToClient(this, wpk);

		SendSysInfo(RES_STRING(GP_PLAYER_CPP_00017));

		m_estop[m_currcha] = true;
		m_worldtick = g_gpsvr->GetCurrentTick();
	}
}

void Player::CountEstopTime() {
	MutexArmor l_lockDB(g_gpsvr->m_mtxDB);
	if (m_estop[m_currcha]) {
		g_gpsvr->m_tblcharaters->EndEstopTime(m_chaid[m_currcha]);
	}
}

void Player::DelEstopPlayer(cChar* plyname) {
	Player* ply = g_gpsvr->FindPlayerByChaName(plyname);
	if (ply) {
		// 角色在线禁言
		ply->m_estop[ply->m_currcha] = false;
	}

	// 数据库操作
	MutexArmor l_lockDB(g_gpsvr->m_mtxDB);
	if (!g_gpsvr->m_tblcharaters->DelEstop(plyname)) {
		char szData[128];
		_snprintf_s(szData, sizeof(szData), _TRUNCATE, RES_STRING(GP_PLAYER_CPP_00018), plyname);
		SendSysInfo(szData);
		return;
	} else {
		char szData[128];
		_snprintf_s(szData, sizeof(szData), _TRUNCATE, RES_STRING(GP_PLAYER_CPP_00019), plyname);
		SendSysInfo(szData);

		char szTemp[128];
		_snprintf_s(szTemp, sizeof(szTemp), _TRUNCATE, RES_STRING(GP_PLAYER_CPP_00020), m_chaname[m_currcha].c_str());
		ply->SendSysInfo(szTemp);

		// 发送禁言命令
		WPacket wpk = g_gpsvr->GetWPacket();
		wpk.WriteCmd(CMD_PT_DEL_ESTOPUSER);
		g_gpsvr->SendToClient(ply, wpk);

		LogLine l_line(g_LogGrpServer);
		l_line << newln << "char[" << m_chaname[m_currcha] << "]may speak plyname:[" << ply->m_chaname[ply->m_currcha] << "]" << endln;
	}
}

void Player::EstopPlayer(cChar* plyname, uLong lTimes) {
	Player* ply = g_gpsvr->FindPlayerByChaName(plyname);
	if (ply) {
		// 角色在线禁言
		ply->m_estop[ply->m_currcha] = true;
	}

	// 数据库操作
	MutexArmor l_lockDB(g_gpsvr->m_mtxDB);
	if (!g_gpsvr->m_tblcharaters->Estop(plyname, lTimes)) {
		char szData[128];
		_snprintf_s(szData, sizeof(szData), _TRUNCATE, RES_STRING(GP_PLAYER_CPP_00023), plyname);
		SendSysInfo(szData);
		return;
	} else {
		char szData[128];
		CFormatParameter param(2);
		param.setString(0, plyname);
		param.setLong(1, lTimes);
		RES_FORMAT_STRING(GP_PLAYER_CPP_00024, param, szData);
		SendSysInfo(szData);

		char szTemp[128];
		CFormatParameter paramTemp(2);
		paramTemp.setString(0, m_chaname[m_currcha].c_str());
		paramTemp.setLong(1, lTimes);
		RES_FORMAT_STRING(GP_PLAYER_CPP_00025, paramTemp, szTemp);
		ply->SendSysInfo(szTemp);

		// 发送禁言命令
		WPacket wpk = g_gpsvr->GetWPacket();
		wpk.WriteCmd(CMD_PT_ESTOPUSER);
		g_gpsvr->SendToClient(ply, wpk);

		LogLine l_line(g_LogGrpServer);
		l_line << newln << "char [" << m_chaname[m_currcha] << "] can't speack plyname:[" << ply->m_chaname[ply->m_currcha] << "]" << lTimes << "minute" << endln;
	}
}

void Player::DisablePlayer(cChar* plyname, uLong lTimes) {
	// 屏蔽角色
	Player* ply = g_gpsvr->FindPlayerByChaName(plyname);
	if (ply) {
		ply->EndPlay(m_gate->GetDataSock());
		if (ply->EndRun()) {
			//向AccountServer发送结束计费命令
			WPacket wpk = g_gpsvr->GetWPacket();
			wpk.WriteCmd(CMD_PA_USER_BILLEND);
			wpk.WriteString(ply->m_acctname.c_str());
			g_gpsvr->SendData(g_gpsvr->m_acctsock, wpk);

			//向AccountServer发送Disable命令
			wpk = g_gpsvr->GetWPacket();
			wpk.WriteCmd(CMD_PA_USER_DISABLE);
			wpk.WriteLong(ply->m_acctLoginID);
			wpk.WriteLong(lTimes);
			g_gpsvr->SendData(g_gpsvr->m_acctsock, wpk);

			//向GateServer发送踢人命令
			wpk = g_gpsvr->GetWPacket();
			wpk.WriteCmd(CMD_AP_KICKUSER);
			g_gpsvr->SendToClient(ply, wpk);

			char szData[128];
			_snprintf_s(szData, sizeof(szData), _TRUNCATE, RES_STRING(GP_PLAYER_CPP_00028), plyname);
			SendSysInfo(szData);

			//踢人成功
			LogLine l_line(g_LogGrpServer);
			l_line << newln << "screen acctid/acctname:[" << ply->m_acctid << "]/[" << ply->m_acctname << "],kill the player!" << endln;
		}
		ply->Free();
	} else {
		int cha_accid;
		if (!g_gpsvr->m_tblcharaters->FetchAccidByChaName(plyname, cha_accid)) {
			char szData[128];
			_snprintf_s(szData, sizeof(szData), _TRUNCATE, RES_STRING(GP_PLAYER_CPP_00031), plyname);
			SendSysInfo(szData);
			return;
		} else {
			//向AccountServer发送Disable命令
			WPacket wpk = g_gpsvr->GetWPacket();
			wpk.WriteCmd(CMD_PA_USER_DISABLE);
			wpk.WriteLong(m_acctLoginID);
			wpk.WriteLong(lTimes);
			g_gpsvr->SendData(g_gpsvr->m_acctsock, wpk);

			char szData[128];
			_snprintf_s(szData, sizeof(szData), _TRUNCATE, RES_STRING(GP_PLAYER_CPP_00032), plyname);
			SendSysInfo(szData);

			//踢人成功
			LogLine l_line(g_LogGrpServer);
			l_line << newln << "recieve screen acctid/plyname:[" << cha_accid << "]/[" << plyname << "]command!" << endln;
		}
	}
}
