/* Generated by Together */

#ifndef GAMESERVERAPP_H
#define GAMESERVERAPP_H

#ifndef USE_IOCP

#include <string>
#include "DBCCommon.h"
#include "PreAlloc.h"
#include "ThreadPool.h"
#include "CommRPC.h"
#include "Point.h"
#include "Identity.h"
//#include "Usage.h"
#include "DataSocket.h"
#include "PacketQueue.h"
#include "Config.h"
#include "gtplayer.h"
#include "util.h"
#include <algorithm>

#pragma pack(push, before_InfoNet)
#pragma pack(8)
#include "InfoNet.h"
#pragma pack(pop, before_InfoNet)

#include "MsgQueue.h"
using namespace dbc;

// GateServer 描述结构
class GameServerApp;
class GateServer {
public:
	GateServer() = default;
	~GateServer() = default;

	void SetDataSock(DataSocket* datasock) {
		m_pCDataSock = datasock;
	}

	void Invalid() {
		m_pCDataSock = nullptr;
	}

	bool IsValid() const { return static_cast<bool>(m_pCDataSock); }

	std::string& GetIP() { return m_strIp; }
	unsigned short& GetPort() { return m_usPort; }
	std::string& GetName() { return m_gtname; }
	//GatePlayer*& GetPlayerList() {return m_playerlist;}
	DataSocket* GetDataSock() { return m_pCDataSock; }

	long SendData(WPacket pkt) {
		if (IsValid() && m_pCDataSock) {
			return m_pCDataSock->SendData(pkt);
		} else {
			return 0;
		}
	}

	GatePlayer* m_listcurplayer{nullptr}; // 用于遍历链表

	// Player 双链表
	GatePlayer* m_playerlist{nullptr};
	int m_playercount{0};
	void AddPlayerCount() { ++m_playercount; }
	void DecPlayerCount() { --m_playercount; }
	int GetPlayerCount() const { return m_playercount; }

protected:
	std::string m_strIp{};
	unsigned short m_usPort{0};
	std::string m_gtname{""};

	DataSocket* m_pCDataSock{nullptr};
};

// 连接 GateServer 任务类
class ConnectGateServer : public Task {
public:
	ConnectGateServer(GameServerApp* gmsvr)
		: m_gmsvr(gmsvr) {}

private:
	virtual long Process() override;
	DWORD dwTimeOut{3'000};
	GameServerApp* m_gmsvr{nullptr};
};

// TradeServer消息队列
class NetMessageQueue : public MsgQueue<pNetMessage> {
public:
	~NetMessageQueue() {
		Clear();
	}

	void Clear() override {
		m_lock.lock();
		for_each(m_queue.begin(), m_queue.end(), FreeNetMessage);
		m_queue.clear();
		m_lock.unlock();
	}
};

// TradeServer服务类
class TradeServer : public InfoNetBase {
public:
	enum {
		CMD_FM_CONNECTED,	// 连上TradeServer
		CMD_FM_DISCONNECTED, // 和TradeServer断开连接
		CMD_FM_MSG,			 // TradeServer发来的消息

		CMD_INFO_MSG_MAX
	};

	TradeServer() = default;
	~TradeServer() = default;

	bool IsValid() const { return bValid; }
	void SetValid() { bValid = true; }
	void InValid() { bValid = false; }

	const std::string& GetIP() const { return m_strIp; }
	const std::string& GetPwd() const { return m_strPwd; }
	unsigned short GetPort() const { return m_usPort; }
	void SetTradeServer(const std::string& strIP, unsigned short usPort, const std::string& strPwd, int nSection) {
		if (usPort) {
			m_strIp = strIP;
			m_usPort = usPort;
			m_strPwd = strPwd;
			m_nSection = nSection;
		}
	}

	void Login();

	//向TradeServer发送消息
	virtual bool SendData(pNetMessage msg) {
		bool bSend = false;
		msg->msgHead.msgSection = m_nSection;

		try {
			bSend = PostInfoSend(msg);
		} catch (...) {
			LG("Store_data", "SendData Error!\n");
		}

		return bSend;
	}

	//取消息队列
	virtual long PeekMsg(unsigned long ms);

	virtual void OnConnect(bool result) override;

	virtual void OnNetMessage(pNetMessage msg) override {
		m_MsgQueue.Push(msg);
	}

	virtual void OnResend(pNetMessage msg) override {}

	virtual void OnDisconnect() override;

protected:
	std::string m_strIp{};
	unsigned short m_usPort{0};
	std::string m_strPwd{};
	int m_nSection{0};
	bool bValid{false};
	NetMessageQueue m_MsgQueue;
};

// 监听 TradeServer 任务类
class ToTradeServer : public Task {
public:
	ToTradeServer(GameServerApp* gmsvr)
		: m_gmsvr(gmsvr) {}

private:
	virtual long Process() override;
	GameServerApp* m_gmsvr{nullptr};
	DWORD m_dwTimeOut{30'000};
};

// Add by lark.li 20090112 begin
class ToMMS;
class ConnectMMS : public Task {
public:
	ConnectMMS(ToMMS* tmms)
		: _tmms(tmms) {}

private:
	virtual long Process() override;
	virtual Task* Lastly() override;

	ToMMS* _tmms{nullptr};
	DWORD _timeout{3'000};
};

class ToMMS : public TcpClientApp, public RPCMGR {
	friend class ConnectMMS;
	struct MMS {
		MMS() {}
		std::string ip;
		uShort port;
		std::string type;
		uShort key;

		DataSocket* datasock{nullptr};
	};

public:
	ToMMS(const char* configeName, ThreadPool* proc, ThreadPool* comm);
	~ToMMS();

	int GetCallTotal() { return m_calltotal; }

	void EnterMap(int accountID, int charaterID, cChar* mapName);
	void LeaveMap(int accountID, int charaterID);

private:
	virtual bool OnConnect(DataSocket* datasock) override;
	virtual void OnDisconnect(DataSocket* datasock, int reason) override;
	virtual void OnProcessData(DataSocket* datasock, RPacket& recvbuf) override;
	virtual WPacket OnServeCall(DataSocket* datasock, RPacket& in_para) override;

	std::atomic<long> m_atexit{0}, m_calltotal{0};
	bool volatile _connected{false};
	MMS m_MMS;
};
// End

class CPlayer;
class UpdateDBCall : public PreAllocTask { // 定时更细任务
public:
	UpdateDBCall(size_t size) : PreAllocTask(size){};
	void Init(CPlayer* pCPlayer) { m_pCPlayer = pCPlayer; }
	long Process() override;

	CPlayer* m_pCPlayer{nullptr};
};

class GoOutServerCall : public PreAllocTask { // 登出GameServer
public:
	GoOutServerCall(size_t size) : PreAllocTask(size){};
	void Init(CPlayer* pCPlayer, bool offLine) {
		m_pCPlayer = pCPlayer;
		m_bOffLine = offLine;
	}
	long Process() override;

	CPlayer* m_pCPlayer{nullptr};
	bool m_bOffLine;
};

class EnterServerCall : public PreAllocTask { // 登出GameServer
public:
	EnterServerCall(size_t size) : PreAllocTask(size){};
	long Process() override;

	GateServer* pGate;
	uLong l_actid;
	const char* pszPassword;
	uLong l_dbid;
	uLong l_worldid;
	cChar* l_map;
	Long lMapCpyNO;
	uLong l_x;
	uLong l_y;
	char chLogin; // 角色上线(0)
	short swiner;
	uintptr_t l_gtaddr;
};

// 网络通信应用类
class GameServerApp : public dbc::TcpClientApp, public dbc::RPCMGR, public PKQueue {
	friend class ConnectGateServer;
	friend class ToTradeServer;
	friend class TradeServer;

public:
	GameServerApp(dbc::ThreadPool* proc, dbc::ThreadPool* comm);
	virtual ~GameServerApp();

	// 登录相关
	char const* GetName() const { return m_strGameName.c_str(); }
	void ConnectGate(GateServer* pGate);
	bool IsValidGate(int i) const;
	GateServer* FindGate(char const* gt_name);

	bool ConnectInfo(TradeServer* pInfo);
	void DisconnectInfo(TradeServer* pInfo);
	TradeServer* GetTradeServer() { return &m_IfServer; }

	// Player 相关 (GateServer内有GatePlayer的一个双链表)
	bool AddPlayer(GatePlayer* gtplayer, GateServer* gt, uintptr_t gtaddr);
	bool DelPlayer(GatePlayer* gtplayer);
	// add by xuedong
	bool BeginGetplayer(GateServer* gt);
	GatePlayer* const GetNextPlayer(GateServer* gt);

	void BeginGetGate();
	GateServer* GetNextGate();
	//

	bool KickPlayer(GatePlayer* gtplayer, long lTimeSec = 0);
	bool KickPlayer2(GatePlayer* gtplayer);

	// 特定发包接口
	bool SendToWorld(WPacket& pkt);
	bool SendToGroup(WPacket& chginf);
	bool SendToClient(GatePlayer* player, WPacket& pkt);
	bool SendToClient(WPacket& pkt, GatePlayer* playerlist);
	bool SendToClient(WPacket& pkt, int array_cnt, uplayer* uplayer_array);
	bool SendToGame(WPacket& pkt, uplayer* uplyr);

protected:
	virtual bool OnConnect(dbc::DataSocket* datasock) override;				  //返回值:true-允许连接,false-不允许连接
	virtual void OnDisconnect(dbc::DataSocket* datasock, int reason) override; //reason值:0-本地程序正常退出；-3-网络被对方关闭；-1-Socket错误;-5-包长度超过限制.
	virtual void OnProcessData(dbc::DataSocket* datasock, dbc::RPacket& recvbuf) override;

	//virtual	bool	OnSendBlock(DataSocket *datasock){return true;}//返回值:true-允许继续等待,false-断开这个连接

	void ProcessData(DataSocket* datasock, RPacket& recvbuf) override;

	//处理TradeServer消息
	void ProcessData(pNetMessage msg, short sType);

public:
	//long 				m_count;
	//dbc::DataSocket	*	m_groupsock;
	//Usage				m_usage;

	PreAllocHeap<UpdateDBCall> m_UpdateProc;
	PreAllocHeap<GoOutServerCall> m_GoOutProc;
	PreAllocHeap<EnterServerCall> m_EnterProc;

private:
	Mutex m_mutdisconn;

	GateServer m_gtarray[MAX_GATE];
	short m_gtnum;
	short m_listcurgt;

	TradeServer m_IfServer;

	std::string m_strGameName;

	uLong m_lastNetCheckTick; // 网络包检查点
	uLong m_netNum;			  // 个数

	uLong m_lastProcCheckTick;
	uLong m_procNum;
};

inline bool GameServerApp::BeginGetplayer(GateServer* gt) {
	if (!gt) {
		return false;
	}
	if (!gt->IsValid()) {
		return false;
	}

	gt->m_listcurplayer = gt->m_playerlist;

	return true;
}

inline GatePlayer* const GameServerApp::GetNextPlayer(GateServer* gt) {
	GatePlayer* pretplayer = gt->m_listcurplayer;
	if (gt->m_listcurplayer) {
		gt->m_listcurplayer = gt->m_listcurplayer->Next;
	}

	return pretplayer;
}

inline void GameServerApp::BeginGetGate() {
	m_listcurgt = 0;
}

inline GateServer* GameServerApp::GetNextGate() {
	while (m_listcurgt < m_gtnum) {
		if (m_gtarray[m_listcurgt++].IsValid()) {
			return m_gtarray + (m_listcurgt - 1);
		}
	}

	return nullptr;
}

extern GameServerApp* g_gmsvr;

inline void uplayer::Init(char const* gt_name, uintptr_t gt_addr, DWORD cha_id) {
	pGate = g_gmsvr->FindGate(gt_name);
	m_dwDBChaId = cha_id;
	m_ulGateAddr = gt_addr;
}

#endif

#endif //GAMESERVERAPP_H
