/* Generated by Together */

#ifndef TEAM_H
#define TEAM_H
#include "PreAlloc.h"
#include "RunBiDirectChain.h"
#include "TeamMember.h"
_DBC_USING
class Player;

/**
 * @alias ΧιΆΣ 
 */
class Team : public PreAllocStru, public RunBiDirectItem<::Team>, public RunBiDirectChain<TeamMember> {
	friend class TeamMember;

public:
	Team(size_t size);
	void Free() override { PreAllocStru::Free(); }
	long BeginRun();
	long EndRun();
	Player* GetLeader();
	Player* GetMember(DWORD dwID);

private:
	~Team();
	void Initially() override;
	void Finally() override;

	Mutex m_mtxTeam;
};
#endif //TEAM_H
