using System;

namespace PkoProxyClient
{
    /// <summary>
    /// Represents the standard PKO protocol Packet ID (Opcode) commands.
    /// Derived completely from source/inc/Common/NetCommand.h.
    /// Covers all client-sent (CM, CP) and client-received (MC, PC) packets.
    /// </summary>
    public enum PkoCommand : ushort
    {
        // ==========================================
        // Client -> GameServer (CM Base = 0)
        // ==========================================
        CMD_CM_SAY = 1,
        CMD_CM_BEGINACTION = 6,
        CMD_CM_ENDACTION = 7,
        CMD_CM_SYNATTR = 8,
        CMD_CM_SYNSKILLBAG = 9,
        CMD_CM_DIE_RETURN = 10,
        CMD_CM_SKILLUPGRADE = 11,
        CMD_CM_PING = 15,
        CMD_CM_REFRESH_DATA = 16,
        CMD_CM_CHECK_PING = 17,
        CMD_CM_MAP_MASK = 18,
        CMD_CM_UPDATEHAIR = 20,
        CMD_CM_TEAM_FIGHT_ASK = 21,
        CMD_CM_TEAM_FIGHT_ASR = 22,
        CMD_CM_ITEM_REPAIR_ASK = 23,
        CMD_CM_ITEM_REPAIR_ASR = 24,
        CMD_CM_ITEM_FORGE_ASK = 25,
        CMD_CM_ITEM_FORGE_ASR = 26,
        CMD_CM_TIGER_START = 27,
        CMD_CM_TIGER_STOP = 28,
        CMD_CM_ITEM_FORGE_CANACTION = 29,
        CMD_CM_KITBAG_LOCK = 31,
        CMD_CM_KITBAG_UNLOCK = 32,
        CMD_CM_KITBAG_CHECK = 33,
        CMD_CM_KITBAG_AUTOLOCK = 34,
        CMD_CM_KITBAGTEMP_SYNC = 35,
        CMD_CM_STORE_OPEN_ASK = 41,
        CMD_CM_STORE_LIST_ASK = 42,
        CMD_CM_STORE_BUY_ASK = 43,
        CMD_CM_STORE_CHANGE_ASK = 44,
        CMD_CM_STORE_QUERY = 45,
        CMD_CM_STORE_VIP = 46,
        CMD_CM_STORE_AFFICHE = 47,
        CMD_CM_STORE_CLOSE = 48,
        CMD_CM_BLACKMARKET_EXCHANGE_REQ = 51,
        CMD_CM_CHEAT_CHECK = 52,
        CMD_CM_VOLUNTER_LIST = 61,
        CMD_CM_VOLUNTER_ADD = 62,
        CMD_CM_VOLUNTER_DEL = 63,
        CMD_CM_VOLUNTER_SEL = 64,
        CMD_CM_VOLUNTER_OPEN = 65,
        CMD_CM_VOLUNTER_ASR = 66,
        CMD_CM_MASTER_INVITE = 71,
        CMD_CM_MASTER_ASR = 72,
        CMD_CM_MASTER_DEL = 73,
        CMD_CM_PRENTICE_DEL = 74,
        CMD_CM_PRENTICE_INVITE = 75,
        CMD_CM_PRENTICE_ASR = 76,
        CMD_CM_LIFESKILL_ASR = 80,
        CMD_CM_LIFESKILL_ASK = 81,
        CMD_CM_BIDUP = 86,
        CMD_CM_SAY2CAMP = 91,
        CMD_CM_GM_SEND = 92,
        CMD_CM_GM_RECV = 93,
        CMD_CM_PK_CTRL = 94,
        CMD_CM_ITEM_LOTTERY_ASK = 95,
        CMD_CM_ITEM_LOTTERY_ASR = 96,
        CMD_CM_CAPTAIN_CONFIRM_ASR = 97,
        CMD_CM_ITEM_AMPHITHEATER_ASK = 98,
        CMD_CM_ITEM_LOCK_ASK = 99,
        CMD_CM_ITEM_UNLOCK_ASK = 100,

        // Task & Role System (RoleBase = 300)
        CMD_CM_REQUESTNPC = 301,
        CMD_CM_REQUESTTALK = 301,
        CMD_CM_TALKPAGE = 302,
        CMD_CM_FUNCITEM = 303,
        CMD_CM_REQUESTTRADE = 308,
        CMD_CM_TRADEITEM = 309,
        CMD_CM_REQUESTAGENCY = 310,
        CMD_CM_CHARTRADE_REQUEST = 312,
        CMD_CM_CHARTRADE_ACCEPT = 313,
        CMD_CM_CHARTRADE_REJECT = 314,
        CMD_CM_CHARTRADE_CANCEL = 315,
        CMD_CM_CHARTRADE_ITEM = 316,
        CMD_CM_CHARTRADE_VALIDATEDATA = 317,
        CMD_CM_CHARTRADE_VALIDATE = 318,
        CMD_CM_CHARTRADE_MONEY = 319,
        CMD_CM_MISSION = 322,
        CMD_CM_MISSIONLIST = 323,
        CMD_CM_MISSIONTALK = 324,
        CMD_CM_MISLOG = 325,
        CMD_CM_MISLOGINFO = 326,
        CMD_CM_MISLOG_CLEAR = 327,
        CMD_CM_STALL_ALLDATA = 330,
        CMD_CM_STALL_OPEN = 331,
        CMD_CM_STALL_BUY = 332,
        CMD_CM_STALL_CLOSE = 333,
        CMD_CM_FORGE = 335,
        CMD_CM_CREATE_BOAT = 338,
        CMD_CM_UPDATEBOAT_PART = 339,
        CMD_CM_BOAT_CANCEL = 340,
        CMD_CM_BOAT_LUANCH = 341,
        CMD_CM_BOAT_BAGSEL = 342,
        CMD_CM_BOAT_SELECT = 343,
        CMD_CM_BOAT_GETINFO = 344,
        CMD_CM_ENTITY_EVENT = 345,
        CMD_CM_CREATE_PASSWORD2 = 346,
        CMD_CM_UPDATE_PASSWORD2 = 347,
        CMD_CM_READBOOK_START = 348,
        CMD_CM_READBOOK_CLOSE = 349,
        CMD_CM_SELECT_TIME_ASK = 350,
        CMD_CM_BEHINDGENIUS_ASK = 351,
        CMD_CM_GET_OUTTIMEEXP = 352,
        CMD_CM_SELECT_COIN_ASK = 353,
        CMD_CM_REQUEST_ANYTIMETRADE = 354,
        CMD_CM_REQUEST_JEWELRYUP_ASK = 355,
        CMD_CM_OPEN_CRYSTALTRADE_ASK = 356,
        CMD_CM_REQUEST_BUY_ASK = 357,
        CMD_CM_REQUEST_SALE_ASK = 358,
        CMD_CM_REQUEST_CANCEL_ASK = 359,
        CMD_CM_REQUEST_GETFLATMONEY = 360,
        CMD_CM_REQUEST_REFRESH_ASK = 361,
        CMD_CM_CHA_CONFIRM_CRYSTALTRADE = 362,
        CMD_CM_GARNER2_REORDER = 371,
        CMD_CM_ANTIINDULGENCE = 372,
        CMD_CM_OPEN_CYCELMISSION = 375,

        // Character select and login commands (CharBase = 430)
        CMD_CM_LOGIN = 431,
        CMD_CM_LOGOUT = 432,
        CMD_CM_BGNPLAY = 433,
        CMD_CM_ENDPLAY = 434,
        CMD_CM_NEWCHA = 435,
        CMD_CM_DELCHA = 436,
        CMD_CM_CANCELEXIT = 437,

        // ==========================================
        // GameServer -> Client (MC Base = 500)
        // ==========================================
        CMD_MC_SAY = 501,
        CMD_MC_MAPCRASH = 503,
        CMD_MC_CHABEGINSEE = 504,
        CMD_MC_CHAENDSEE = 505,
        CMD_MC_ITEMBEGINSEE = 506,
        CMD_MC_ITEMENDSEE = 507,
        CMD_MC_NOTIACTION = 508,
        CMD_MC_SYNATTR = 509,
        CMD_MC_SYNSKILLBAG = 510,
        CMD_MC_SYNASKILLSTATE = 511,
        CMD_MC_PING = 515,
        CMD_MC_ENTERMAP = 516,
        CMD_MC_SYSINFO = 517,
        CMD_MC_ALARM = 518,
        CMD_MC_TEAM = 519,
        CMD_MC_FAILEDACTION = 520,
        CMD_MC_MESSAGE = 521,
        CMD_MC_ASTATEBEGINSEE = 522,
        CMD_MC_ASTATEENDSEE = 523,
        CMD_MC_TLEADER_ID = 524,
        CMD_MC_CHA_EMOTION = 525,
        CMD_MC_QUERY_CHA = 526,
        CMD_MC_QUERY_CHAITEM = 527,
        CMD_MC_CALL_CHA = 528,
        CMD_MC_GOTO_CHA = 529,
        CMD_MC_KICK_CHA = 530,
        CMD_MC_SYNDEFAULTSKILL = 531,
        CMD_MC_ADD_ITEM_CHA = 532,
        CMD_MC_DEL_ITEM_CHA = 533,
        CMD_MC_QUERY_CHAPING = 534,
        CMD_MC_QUERY_RELIVE = 535,
        CMD_MC_PREMOVE_TIME = 536,
        CMD_MC_CHECK_PING = 537,
        CMD_MC_MAP_MASK = 538,
        CMD_MC_OPENHAIR = 539,
        CMD_MC_UPDATEHAIR_RES = 540,
        CMD_MC_EVENT_INFO = 541,
        CMD_MC_SIDE_INFO = 542,
        CMD_MC_TEAM_FIGHT_ASK = 543,
        CMD_MC_ITEM_REPAIR_ASK = 544,
        CMD_MC_ITEM_REPAIR_ASR = 545,
        CMD_MC_BEGIN_ITEM_REPAIR = 546,
        CMD_MC_APPEND_LOOK = 547,
        CMD_MC_ITEM_FORGE_ASK = 548,
        CMD_MC_ITEM_FORGE_ASR = 549,
        CMD_MC_ITEM_USE_SUC = 550,
        CMD_MC_KITBAG_CAPACITY = 551,
        CMD_MC_ESPE_ITEM = 552,
        CMD_MC_KITBAG_CHECK_ASR = 553,
        CMD_MC_KITBAGTEMP_SYNC = 554,
        CMD_MC_STORE_OPEN_ASR = 561,
        CMD_MC_STORE_LIST_ASR = 562,
        CMD_MC_STORE_BUY_ASR = 563,
        CMD_MC_STORE_CHANGE_ASR = 564,
        CMD_MC_STORE_QUERY = 565,
        CMD_MC_STORE_VIP = 566,
        CMD_MC_STORE_AFFICHE = 567,
        CMD_MC_POPUP_NOTICE = 568,
        CMD_MC_BLACKMARKET_EXCHANGEDATA = 571,
        CMD_MC_BLACKMARKET_EXCHANGE_ASR = 572,
        CMD_MC_BLACKMARKET_EXCHANGEUPDATE = 573,
        CMD_MC_BLACKMARKET_TRADEUPDATE = 574,
        CMD_MC_EXCHANGEDATA = 575,
        CMD_MC_VOLUNTER_LIST = 581,
        CMD_MC_VOLUNTER_STATE = 582,
        CMD_MC_VOLUNTER_SEL = 583,
        CMD_MC_VOLUNTER_OPEN = 584,
        CMD_MC_VOLUNTER_ASK = 585,
        CMD_MC_LISTAUCTION = 586,
        CMD_MC_MASTER_ASK = 591,
        CMD_MC_PRENTICE_ASK = 592,
        CMD_MC_CHAPLAYEFFECT = 593,
        CMD_MC_SAY2CAMP = 596,
        CMD_MC_GM_MAIL = 597,
        CMD_MC_CHEAT_CHECK = 598,
        CMD_CM_ITEM_LOCK_ASR = 599,
        CMD_MC_ITEM_UNLOCK_ASR = 595,

        // Life Skill & Arena Responses (MC Base + 100)
        CMD_MC_LIFESKILL_BGING = 600,
        CMD_MC_LIFESKILL_ASR = 601,
        CMD_MC_LIFESKILL_ASK = 602,
        CMD_MC_ITEM_LOTTERY_ASK = 603,
        CMD_MC_ITEM_LOTTERY_ASR = 604,
        CMD_MC_CAPTAIN_ASK = 605,
        CMD_MC_ITEM_AMPHITHEATER_ASR = 606,
        CMD_MC_REQUEST_JEWELRYUP_ASR = 607,

        // Character select and login responses (CharBase = 930)
        CMD_MC_LOGIN = 931,
        CMD_MC_LOGOUT = 932,
        CMD_MC_BGNPLAY = 933,
        CMD_MC_ENDPLAY = 934,
        CMD_MC_NEWCHA = 935,
        CMD_MC_DELCHA = 936,
        CMD_MC_CHAPSTR = 940,

        // ==========================================
        // Client -> GroupServer (CP Base = 6000)
        // ==========================================
        CMD_CP_TEAM_INVITE = 6001,
        CMD_CP_TEAM_ACCEPT = 6002,
        CMD_CP_TEAM_REFUSE = 6003,
        CMD_CP_TEAM_LEAVE = 6004,
        CMD_CP_TEAM_KICK = 6005,
        CMD_CP_FRND_INVITE = 6011,
        CMD_CP_FRND_ACCEPT = 6012,
        CMD_CP_FRND_REFUSE = 6013,
        CMD_CP_FRND_DELETE = 6014,
        CMD_CP_FRND_MOVE_GROUP = 6015,
        CMD_CP_FRND_REFRESH_INFO = 6016,
        CMD_CP_CHANGE_PERSONINFO = 6017,
        CMD_CP_FRND_DEL_GROUP = 6018,
        CMD_CP_FRND_ADD_GROUP = 6019,
        CMD_CP_FRND_CHANGE_GROUP = 6020,
        CMD_CP_QUERY_PERSONINFO = 6021,
        CMD_CP_PING = 6025,
        CMD_CP_REPORT_WG = 6026,
        CMD_CP_MASTER_REFRESH_INFO = 6031,
        CMD_CP_PRENTICE_REFRESH_INFO = 6032,
        CMD_CP_GUILD_INVITE = 6033,
        CMD_CP_GUILD_ACCEPT = 6034,
        CMD_CP_GUILD_REFUSE = 6035,
        CMD_CP_GM1SAY = 6400,
        CMD_CP_SAY2TRADE = 6401,
        CMD_CP_SAY2ALL = 6402,
        CMD_CP_SAY2YOU = 6403,
        CMD_CP_SAY2TEM = 6404,
        CMD_CP_SAY2GUD = 6405,
        CMD_CP_SESS_CREATE = 6406,
        CMD_CP_SESS_SAY = 6407,
        CMD_CP_SESS_ADD = 6408,
        CMD_CP_SESS_LEAVE = 6409,
        CMD_CP_REFUSETOME = 6410,
        CMD_CP_GM1SAY1 = 6411,
        CMD_CP_GMSAY = 6412,

        // ==========================================
        // GroupServer -> Client (PC Base = 5000)
        // ==========================================
        CMD_PC_TEAM_INVITE = 5001,
        CMD_PC_TEAM_REFRESH = 5002,
        CMD_PC_TEAM_CANCEL = 5003,
        CMD_PC_FRND_INVITE = 5011,
        CMD_PC_FRND_REFRESH = 5012,
        CMD_PC_FRND_CANCEL = 5013,
        CMD_PC_FRND_MOVE_GROUP = 5015,
        CMD_PC_FRND_REFRESH_INFO = 5016,
        CMD_PC_CHANGE_PERSONINFO = 5017,
        CMD_PC_FRND_DEL_GROUP = 5018,
        CMD_PC_FRND_ADD_GROUP = 5019,
        CMD_PC_FRND_CHANGE_GROUP = 5020,
        CMD_PC_QUERY_PERSONINFO = 5021,
        CMD_PC_PING = 5025,
        CMD_PC_GUILD = 5030,
        CMD_PC_GUILD_INVITE = 5031,
        CMD_PC_GUILD_CANCEL = 5033,
        CMD_PC_MASTER_REFRESH = 5041,
        CMD_PC_MASTER_CANCEL = 5042,
        CMD_PC_MASTER_REFRESH_INFO = 5043,
        CMD_PC_PRENTICE_REFRESH_INFO = 5044,
        CMD_PC_GM1SAY = 5400,
        CMD_PC_SAY2TRADE = 5401,
        CMD_PC_SAY2ALL = 5402,
        CMD_PC_SAY2YOU = 5403,
        CMD_PC_SAY2TEM = 5404,
        CMD_PC_SAY2GUD = 5405,
        CMD_PC_SESS_CREATE = 5406,
        CMD_PC_SESS_SAY = 5407,
        CMD_PC_SESS_ADD = 5408,
        CMD_PC_SESS_LEAVE = 5409,
        CMD_PC_GM1SAY1 = 5411,
        CMD_PC_GARNER2_ORDER = 5101
    }

    /// <summary>
    /// Translates PKO command packet IDs to readable string macro names using the PkoCommand C# enum.
    /// </summary>
    public static class PkoCommandTranslator
    {
        /// <summary>
        /// Translates a Packet ID (Opcode) into its readable macro name.
        /// </summary>
        public static string GetCommandName(int packetId)
        {
            if (Enum.IsDefined(typeof(PkoCommand), (ushort)packetId))
            {
                return ((PkoCommand)packetId).ToString();
            }

            return $"CMD_UNKNOWN_{packetId}";
        }
    }
}
